"""Generated analog cells.

Generated by .github/generate_cells.py. Do not edit by hand.
Run ``make cells-regen`` to regenerate, ``make cells-check`` to verify.
"""

from __future__ import annotations

import gdsfactory as gf
from gdsfactory import components as _components
from gdsfactory.components.analog.transformers import (
    via3 as _default_via3,
)
from gdsfactory.typings import *  # noqa: F403

from gpdk.cells._schematic import (
    capacitor_schematic,
    inductor_schematic,
)


@gf.cell(tags=["analog"], schematic_function=inductor_schematic)
def inductor(
    width: float = 2.0,
    space: float = 2.1,
    diameter: float = 25.35,
    resistance: float = 0.5777,
    inductance: float = 3.3303e-11,
    turns: int = 1,
    layer_metal: LayerSpec = "M3",
    layer_inductor: LayerSpec = "M1",
    layer_metal_pin: LayerSpec = "WG_PIN",
    layers_no_fill: LayerSpecs = ("DEVREC", "NO_TILE_SI"),
) -> gf.Component:
    r"""Create a 2-turn inductor.

    Args:
        width: Width of the inductor trace in micrometers.
        space: Space between turns in micrometers.
        diameter: Inner diameter in micrometers.
        resistance: Resistance in ohms.
        inductance: Inductance in henries.
        turns: Number of turns (default 1 for inductor2).
        layer_metal: Layer for the metal trace.
        layer_inductor: Layer for the inductor region.
        layer_metal_pin: Layer for the metal pins.
        layers_no_fill: Layers to exclude from fill.

    Returns:
        Component with inductor layout.
    """
    return _components.inductor(
        width=width,
        space=space,
        diameter=diameter,
        resistance=resistance,
        inductance=inductance,
        turns=turns,
        layer_metal=layer_metal,
        layer_inductor=layer_inductor,
        layer_metal_pin=layer_metal_pin,
        layers_no_fill=layers_no_fill,
    )


@gf.cell(tags=["analog"], schematic_function=capacitor_schematic)
def interdigital_capacitor(
    fingers: int = 4,
    finger_length: float | int = 20.0,
    finger_gap: float | int = 2.0,
    thickness: float | int = 5.0,
    layer: LayerSpec = "WG",
) -> gf.Component:
    r"""Generate an interdigital capacitor component with ports on both ends.

    An interdigital capacitor consists of interleaved metal fingers that create
    a distributed capacitance. This component creates a planar capacitor with
    two sets of interleaved fingers extending from opposite ends.

    See for example Zhu et al., `Accurate circuit model of interdigital
    capacitor and its application to design of new quasi-lumped miniaturized
    filters with suppression of harmonic resonance`, doi: 10.1109/22.826833.

    Note:
        ``finger_length=0`` effectively provides a parallel plate capacitor.
        The capacitance scales approximately linearly with the number of fingers
        and finger length.

    Args:
        fingers: Total number of fingers of the capacitor (must be >= 1).
        finger_length: Length of each finger in μm.
        finger_gap: Gap between adjacent fingers in μm.
        thickness: Thickness of fingers and the base section in μm.
        layer: Layer specification for the capacitor geometry.

    Returns:
        Component: A gdsfactory component with the interdigital capacitor geometry
        and two ports ('o1' and 'o2') on opposing sides.
    """
    return _components.interdigital_capacitor(
        fingers=fingers,
        finger_length=finger_length,
        finger_gap=finger_gap,
        thickness=thickness,
        layer=layer,
    )


@gf.cell(tags=["analog"])
def interdigitated_electrodes(
    n_fingers: int = 10,
    finger_width: float = 0.5,
    finger_length: float = 10.0,
    finger_gap: float = 0.5,
    bus_width: float = 2.0,
    bus_length: float | None = None,
    layer: LayerSpec = "MTOP",
    port_type: str = "electrical",
) -> gf.Component:
    r"""Interdigitated electrode pattern.

    Two horizontal bus bars (top and bottom) with alternating fingers extending
    from each bus toward the opposite one. Fingers from the top bus extend
    downward and fingers from the bottom bus extend upward, interleaving
    with a gap between the finger tips and the opposite bus.

    Args:
        n_fingers: Total number of fingers (split between top and bottom buses).
        finger_width: Width of each finger in um.
        finger_length: Length of each finger in um.
        finger_gap: Gap between adjacent fingers (edge to edge) in um.
        bus_width: Width (height) of each bus bar in um.
        bus_length: Length of each bus bar in um. Defaults to the total width
            needed to accommodate all fingers.
        layer: Layer specification for all geometry.
        port_type: Port type for electrical ports at bus bar ends.
    """
    return _components.interdigitated_electrodes(
        n_fingers=n_fingers,
        finger_width=finger_width,
        finger_length=finger_length,
        finger_gap=finger_gap,
        bus_width=bus_width,
        bus_length=bus_length,
        layer=layer,
        port_type=port_type,
    )


@gf.cell(tags=["analog"])
def stacked_transformer(
    d_out: float = 150.0,
    N1: int = 3,
    N2: int = 3,
    sides: int = 8,
    width: float = 10.0,
    spacing: float = 2.0,
    center_tap_primary: bool = False,
    center_tap_secondary: bool = False,
    via_extent: float | None = None,
    port_spacing: float | None = None,
    via_primary: ComponentSpec = _default_via3,
    via_secondary: ComponentSpec = "via1",
    resistance: float = 0.5777,
    inductance: float = 3.3303e-11,
    add_pgs: bool = False,
    pgs_diameter: float = 180.0,
    pgs_width: float = 4.0,
    pgs_spacing: float = 2.0,
    layer_winding_primary: LayerSpec | None = None,
    layer_crossing_primary: LayerSpec = "M3",
    layer_winding_secondary: LayerSpec = "M2",
    layer_crossing_secondary: LayerSpec = "M1",
    layers_pgs: LayerSpecs = (),
) -> gf.Component:
    r"""Stacked transformer.

    The primary winding sits on layer_winding_primary with
    its crossings on layer_crossing_primary (connected by via_primary);
    the secondary winding sits on layer_winding_secondary with its
    crossings on layer_crossing_secondary (connected by via_secondary),
    mirrored to sit on the opposite side of d_out so the two windings
    stack vertically over the same footprint.

    LAYER STACK: this gdsfactory generic PDK only has 3 real metals
    (M1/M2/M3). A fully isolated stacked transformer needs 4 independent
    metals (primary winding, primary crossing, secondary winding,
    secondary crossing), so the defaults here use an EXTRA, non-native
    4th metal registered via gf.kcl.layer() at import time (M4_LAYER,
    layer (53, 0)) with its own via (via3(), VIA3_LAYER, layer (48, 0))
    connecting it to M3. This gives full primary/secondary isolation by
    default:
        layer_winding_primary=M4_LAYER, layer_crossing_primary="M3", via_primary=via3
        layer_winding_secondary="M2",   layer_crossing_secondary="M1", via_secondary="via1"

    M4_LAYER/VIA3_LAYER are valid GDS layers but are NOT part of this PDK's real,
    fabricatable metal stack. If you need this component to be simulation-ready
    (Palace/gsim meshing) ortape-out-accurate, call get_extended_layer_stack()
    instead of the PDK's default stack, e.g. sim.set_stack(stack=get_extended_layer_stack()).

    If your ACTUAL target PDK has a genuine 4th metal, pass its real
    layer name/via in place of M4_LAYER/via3 instead of relying on this
    synthetic one.

    layers_pgs defaults to an empty tuple: even with M4 in play, all of
    M1/M2/M3/M4 are live signal layers in the default configuration, so
    there's still no obviously-safe spare metal for a patterned ground
    shield — pass an explicit LayerSpecs of your own (accepting whatever
    coupling that implies) if you need one anyway.

    Args:
        d_out: Outer diameter of each winding, in micrometers.
        N1: Number of turns in the primary winding.
        N2: Number of turns in the secondary winding.
        sides: Number of polygon sides per full turn (8 = octagonal).
        width: Metal trace width in micrometers.
        spacing: Gap between adjacent turns in micrometers.
        center_tap_primary: When True, add a center-tap bridge and CT_P
            port to the primary winding.
        center_tap_secondary: When True, add a center-tap bridge and CT_S
            port to the secondary winding.
        via_extent: Length crossing routes extend past their crossing box,
            and the box size used to size the crossing/centertap via
            arrays, for both halves. If None, it's derived independently
            for each half from that half's own via geometry (same
            derivation spiral_inductor/symmetric_inductor use).
        port_spacing: Horizontal spacing of both differential port pairs.
            Defaults to spacing.
        via_primary: via ComponentSpec connecting layer_winding_primary <-> layer_crossing_primary.
        via_secondary: via ComponentSpec connecting layer_winding_secondary <-> layer_crossing_secondary.
        resistance: Series resistance in ohms, stored as metadata only.
        inductance: Inductance in henries, stored as metadata only.
        add_pgs: When True, add a patterned ground shield on layers_pgs.
            See the layer-stack caveat above before enabling this.
        pgs_diameter: Bounding size D of the ground shield square, in micrometers.
        pgs_width: Strip width w of each ground shield finger, in micrometers.
        pgs_spacing: Gap s between adjacent ground shield fingers, in micrometers.
        layer_winding_primary: Metal layer for the primary winding.
        layer_crossing_primary: Metal layer for the primary crossings.
        layer_winding_secondary: Metal layer for the secondary winding.
        layer_crossing_secondary: Metal layer for the secondary crossings.
        layers_pgs: Layers on which the patterned ground shield is drawn.

    Returns:
        Component with 4-6 ports:
          P+ / P-    ->  primary differential terminals   (layer_winding_primary)
          S+ / S-    ->  secondary differential terminals (layer_winding_secondary)
          CT_P       ->  present if center_tap_primary=True
          CT_S       ->  present if center_tap_secondary=True
    """
    return _components.stacked_transformer(
        d_out=d_out,
        N1=N1,
        N2=N2,
        sides=sides,
        width=width,
        spacing=spacing,
        center_tap_primary=center_tap_primary,
        center_tap_secondary=center_tap_secondary,
        via_extent=via_extent,
        port_spacing=port_spacing,
        via_primary=via_primary,
        via_secondary=via_secondary,
        resistance=resistance,
        inductance=inductance,
        add_pgs=add_pgs,
        pgs_diameter=pgs_diameter,
        pgs_width=pgs_width,
        pgs_spacing=pgs_spacing,
        layer_winding_primary=layer_winding_primary,
        layer_crossing_primary=layer_crossing_primary,
        layer_winding_secondary=layer_winding_secondary,
        layer_crossing_secondary=layer_crossing_secondary,
        layers_pgs=layers_pgs,
    )


@gf.cell(tags=["analog"])
def symmetric_transformer(
    d_out: float = 150.0,
    N1: int = 2,
    N2: int = 3,
    sides: int = 8,
    width: float = 7.0,
    spacing: float = 2.0,
    center_tap_primary: bool = False,
    center_tap_secondary: bool = False,
    via_extent: float | None = None,
    port_spacing: float | None = None,
    via: ComponentSpec = "via2",
    resistance: float = 0.5777,
    inductance: float = 3.3303e-11,
    add_pgs: bool = False,
    pgs_diameter: float = 180.0,
    pgs_width: float = 4.0,
    pgs_spacing: float = 2.0,
    layer_winding: LayerSpec = "M3",
    layer_underpass: LayerSpec = "M2",
    layers_pgs: LayerSpecs = ("M1",),
) -> gf.Component:
    r"""Symmetric (interleaved) transformer.

    Two interleaved windings (primary: N1 turns, secondary: N2 turns) share
    the same octagonal spiral, alternating turn-by-turn. Crossings are
    routed on layer_underpass wherever a turn boundary needs to jump
    between quadrants; bridges wire together the top/bottom/left/right
    quadrant segments directly on layer_winding.

    Args:
        d_out: Outer diameter of the winding structure, in micrometers.
        N1: Number of turns in the primary winding.
        N2: Number of turns in the secondary winding.
        sides: Number of polygon sides per full turn (8 = octagonal).
            Must be a multiple of 4 (quadrant angle lists use sides // 4).
        width: Metal trace width in micrometers.
        spacing: Gap between adjacent turns in micrometers.
        center_tap_primary: When True, add a center-tap bridge (and CT1 or
            CT2 port, depending on parity) for the primary winding.
        center_tap_secondary: When True, add a center-tap bridge (and CT1
            or CT2 port, depending on parity) for the secondary winding.
        via_extent: Length crossing/bridge routes extend past their
            crossing box on layer_underpass, and the box size used to size
            the crossing/centertap via arrays. If None, it's derived from
            the chosen via's own geometry the same way spiral_inductor and
            symmetric_inductor derive their "extend" value.
        port_spacing: Horizontal spacing of the differential port pairs.
        via: via ComponentSpec connecting winding <-> crossing/centertap.
        resistance: Series resistance in ohms, stored as metadata only.
        inductance: Inductance in henries, stored as metadata only.
        add_pgs: When True, add a patterned ground shield on layers_pgs.
        pgs_diameter: Bounding size D of the ground shield square, in micrometers.
        pgs_width: Strip width w of each ground shield finger, in micrometers.
        pgs_spacing: Gap s between adjacent ground shield fingers, in micrometers.
        layer_winding: Metal layer for the main winding (top metal).
        layer_underpass: Metal layer for crossings and center-tap bridges (one layer below layer_winding).
        layers_pgs: Layers on which the patterned ground shield is drawn,
            kept separate from both layer_winding and layer_underpass

    Returns:
        Component with 4-6 ports:
          P1+ / P1-  ->  primary differential terminals   (bottom, layer_winding)
          P2+ / P2-  ->  secondary differential terminals (top, layer_winding)
          CT1        ->  present if a center tap lands on the bottom side
          CT2        ->  present if a center tap lands on the top side
    """
    return _components.symmetric_transformer(
        d_out=d_out,
        N1=N1,
        N2=N2,
        sides=sides,
        width=width,
        spacing=spacing,
        center_tap_primary=center_tap_primary,
        center_tap_secondary=center_tap_secondary,
        via_extent=via_extent,
        port_spacing=port_spacing,
        via=via,
        resistance=resistance,
        inductance=inductance,
        add_pgs=add_pgs,
        pgs_diameter=pgs_diameter,
        pgs_width=pgs_width,
        pgs_spacing=pgs_spacing,
        layer_winding=layer_winding,
        layer_underpass=layer_underpass,
        layers_pgs=layers_pgs,
    )


@gf.cell
def via3(
    size: tuple[float, float] = (0.7, 0.7),
    enclosure: float = 1.0,
    pitch: float = 2.0,
) -> gf.Component:
    r"""Via connecting M3 <-> M4, mirroring via1/via2/viac's shape (0.7x0.7um squares, 1um enclosure, 2um pitch) but on VIA3_LAYER.

    Only meaningful once M4 also has real z-geometry — see
    get_extended_layer_stack() for the matching LayerStack entry.

    Args:
        size: see :func:`gdsfactory.components.analog.transformers.via3` for details.
        enclosure: see :func:`gdsfactory.components.analog.transformers.via3` for details.
        pitch: see :func:`gdsfactory.components.analog.transformers.via3` for details.
    """
    return _components.via3(
        size=size,
        enclosure=enclosure,
        pitch=pitch,
    )


__all__ = [
    "inductor",
    "interdigital_capacitor",
    "interdigitated_electrodes",
    "stacked_transformer",
    "symmetric_transformer",
    "via3",
]
