"""Generated filters cells.

Generated by .github/generate_cells.py. Do not edit by hand.
Run ``make cells-regen`` to regenerate, ``make cells-check`` to verify.
"""

from __future__ import annotations

import gdsfactory as gf
from gdsfactory import components as _components
from gdsfactory.components.filters.awg import (
    free_propagation_region_input as _default_free_propagation_region_input,
)
from gdsfactory.components.filters.awg import (
    free_propagation_region_output as _default_free_propagation_region_output,
)
from gdsfactory.components.filters.mode_converter import (
    bend_s as _default_bend_s,
)
from gdsfactory.components.filters.mode_converter import (
    partial as _default_partial,
)
from gdsfactory.components.filters.terminator import (
    strip as _default_strip,
)
from gdsfactory.typings import *  # noqa: F403

from gpdk.cells._schematic import (
    ckt_schematic,
    terminator_schematic,
)


@gf.cell(tags=["filters"])
def awg(
    arms: int = 10,
    outputs: int = 3,
    free_propagation_region_input_function: ComponentSpec = _default_free_propagation_region_input,
    free_propagation_region_output_function: ComponentSpec = _default_free_propagation_region_output,
    fpr_spacing: float = 50.0,
    arm_spacing: float = 1.0,
    length_increment: float = 0.0,
    cross_section: CrossSectionSpec = "strip",
) -> gf.Component:
    r"""Returns an Arrayed Waveguide grating.

    To simulate you can use
    https://github.com/dnrobin/awg-python

    Args:
        arms: number of arms.
        outputs: number of outputs.
        free_propagation_region_input_function: for input.
        free_propagation_region_output_function: for output.
        fpr_spacing: x separation between input/output free propagation region.
        arm_spacing: y separation between arms (used when length_increment == 0).
        length_increment: constant length step dL (um); when > 0 the arms form a
            nested fan where arm i is exactly i*dL longer than arm 0 -- the property
            that makes an AWG disperse light by wavelength.
        cross_section: cross_section function.
    """
    return _components.awg(
        arms=arms,
        outputs=outputs,
        free_propagation_region_input_function=free_propagation_region_input_function,
        free_propagation_region_output_function=free_propagation_region_output_function,
        fpr_spacing=fpr_spacing,
        arm_spacing=arm_spacing,
        length_increment=length_increment,
        cross_section=cross_section,
    )


@gf.cell(tags=["filters"])
def dbr(
    w1: float = 0.45,
    w2: float = 0.55,
    l1: float = 0.159,
    l2: float = 0.159,
    n: int = 10,
    cross_section: CrossSectionSpec = "strip",
    straight_length: float = 0.01,
) -> gf.Component:
    r"""Distributed Bragg Reflector.

    Args:
        w1: thin width in um.
        w2: thick width in um.
        l1: thin length in um.
        l2: thick length in um.
        n: number of periods.
        cross_section: cross_section spec.
        straight_length: length of the straight section between cutbacks.

           l1      l2
        <-----><-------->
                _________
        _______|

          w1       w2       ...  n times
        _______
               |_________
    """
    return _components.dbr(
        w1=w1,
        w2=w2,
        l1=l1,
        l2=l2,
        n=n,
        cross_section=cross_section,
        straight_length=straight_length,
    )


@gf.cell(tags=["filters"])
def dbr_cell(
    w1: float = 0.45,
    w2: float = 0.55,
    l1: float = 0.159,
    l2: float = 0.159,
    cross_section: CrossSectionSpec = "strip",
) -> gf.Component:
    r"""Distributed Bragg Reflector unit cell.

    Args:
        w1: thin width in um.
        l1: thin length in um.
        w2: thick width in um.
        l2: thick length in um.
        n: number of periods.
        cross_section: cross_section spec.

           l1      l2
        <-----><-------->
                _________
        _______|

          w1       w2
        _______
               |_________
    """
    return _components.dbr_cell(
        w1=w1,
        w2=w2,
        l1=l1,
        l2=l2,
        cross_section=cross_section,
    )


@gf.cell(tags=["filters"])
def dbr_tapered(
    length: float = 10.0,
    period: float = 0.85,
    dc: float = 0.5,
    w1: float = 0.4,
    w2: float = 1.0,
    taper_length: float = 20.0,
    fins: bool = False,
    fin_size: Size = (0.2, 0.05),
    cross_section: CrossSectionSpec = "strip",
) -> gf.Component:
    r"""Distributed Bragg Reflector Cell class.

    Tapers the input straight to a
    periodic straight structure with varying width (1-D photonic crystal).

    Args:
       length: Length of the DBR region.
       period: Period of the repeated unit.
       dc: Duty cycle of the repeated unit (must be a float between 0 and 1.0).
       w1: thin section width. w1 = 0 corresponds to disconnected periodic blocks.
       w2: wide section width.
       taper_length: between the input/output straight and the DBR region.
       fins: If `True`, adds fins to the input/output straights.
       fin_size: Specifies the x- and y-size of the `fins`. Defaults to 200 nm x 50 nm
       cross_section: cross_section spec.

                 period
        <-----><-------->
                _________
        _______|

          w1       w2       ...  n times
        _______
               |_________
    """
    return _components.dbr_tapered(
        length=length,
        period=period,
        dc=dc,
        w1=w1,
        w2=w2,
        taper_length=taper_length,
        fins=fins,
        fin_size=fin_size,
        cross_section=cross_section,
    )


@gf.cell(tags=["filters"])
def fiber(
    core_diameter: float = 10,
    cladding_diameter: float = 125,
    layer_core: LayerSpec = "WG",
    layer_cladding: LayerSpec = "WGCLAD",
) -> gf.Component:
    r"""Returns a fiber.

    Args:
        core_diameter: in um.
        cladding_diameter: in um.
        layer_core: layer spec for fiber core.
        layer_cladding: layer spec for fiber cladding.
    """
    return _components.fiber(
        core_diameter=core_diameter,
        cladding_diameter=cladding_diameter,
        layer_core=layer_core,
        layer_cladding=layer_cladding,
    )


@gf.cell(tags=["filters"])
def fiber_array(
    n: int = 8,
    pitch: float = 127.0,
    core_diameter: float = 10,
    cladding_diameter: float = 125,
    layer_core: LayerSpec = "WG",
    layer_cladding: LayerSpec = "WGCLAD",
) -> gf.Component:
    r"""Returns a fiber array.

    Args:
        n: number of fibers.
        pitch: spacing.
        core_diameter: 10um.
        cladding_diameter: in um.
        layer_core: layer spec for fiber core.
        layer_cladding: layer spec for fiber cladding.

    ```text
        pitch
         <->
        _________
       |         | lid
       | o o o o |
       |         | base
       |_________|
          length
    ```
    """
    return _components.fiber_array(
        n=n,
        pitch=pitch,
        core_diameter=core_diameter,
        cladding_diameter=cladding_diameter,
        layer_core=layer_core,
        layer_cladding=layer_cladding,
    )


@gf.cell(tags=["filters"])
def free_propagation_region(
    width1: float = 2.0,
    width2: float = 20.0,
    length: float = 20.0,
    wg_width: float = 0.5,
    inputs: int = 1,
    outputs: int = 10,
    cross_section: CrossSectionSpec = "strip",
) -> gf.Component:
    r"""Free propagation region.

    Args:
        width1: width of the input region.
        width2: width of the output region.
        length: length of the free propagation region.
        wg_width: waveguide width.
        inputs: number of inputs.
        outputs: number of outputs.
        cross_section: cross_section function.

                 length
                 <-->
                   /|
                  / |
           width1|  | width2
                  \ |
                   \|
    """
    return _components.free_propagation_region(
        width1=width1,
        width2=width2,
        length=length,
        wg_width=wg_width,
        inputs=inputs,
        outputs=outputs,
        cross_section=cross_section,
    )


@gf.cell(tags=["filters"])
def loop_mirror(
    component: ComponentSpec = "mmi1x2",
    bend90: ComponentSpec = "bend_euler",
    cross_section: CrossSectionSpec = "strip",
) -> gf.Component:
    r"""Returns Sagnac loop_mirror.

    Args:
        component: 1x2 splitter.
        bend90: 90 deg bend.
        cross_section: cross_section settings.
    """
    return _components.loop_mirror(
        component=component,
        bend90=bend90,
        cross_section=cross_section,
    )


@gf.cell(tags=["filters"], schematic_function=ckt_schematic)
def mode_converter(
    gap: float = 0.3,
    length: float = 10,
    coupler_straight_asymmetric: ComponentSpec = "coupler_straight_asymmetric",
    bend: ComponentSpec = _default_partial(_default_bend_s, size=(25, 3)),
    taper: ComponentSpec = "taper",
    mm_width: float = 1.2,
    mc_mm_width: float = 1,
    sm_width: float = 0.5,
    taper_length: float = 25,
    cross_section: CrossSectionSpec = "strip",
) -> gf.Component:
    r"""Returns Mode converter from TE0 to TE1.

    By matching the effective indices of two waveguides with different widths,
    light can couple from different transverse modes e.g. TE0 <-> TE1.
    https://doi.org/10.1109/JPHOT.2019.2941742

    Args:
        gap: directional coupler gap.
        length: coupler length interaction.
        coupler_straight_asymmetric: spec.
        bend: spec.
        taper: spec.
        mm_width: input/output multimode waveguide width.
        mc_mm_width: mode converter multimode waveguide width
        sm_width: single mode waveguide width.
        taper_length: taper length.
        cross_section: cross_section spec.

        o2 ---           --- o4
              \         /
               \       /
                -------
        o1 -----=======----- o3
                |-----|
                length

        = : multimode width
        - : singlemode width
    """
    return _components.mode_converter(
        gap=gap,
        length=length,
        coupler_straight_asymmetric=coupler_straight_asymmetric,
        bend=bend,
        taper=taper,
        mm_width=mm_width,
        mc_mm_width=mc_mm_width,
        sm_width=sm_width,
        taper_length=taper_length,
        cross_section=cross_section,
    )


@gf.cell(tags=["filters"])
def polarization_splitter_rotator(
    width_taper_in: Float3 = (0.54, 0.69, 0.83),
    length_taper_in: Float2 | Float3 = (4.0, 44.0),
    width_coupler: Float2 = (0.9, 0.404),
    length_coupler: float = 7.0,
    gap: float = 0.15,
    width_out: float = 0.54,
    length_out: float = 14.33,
    dy: Delta = 5.0,
    cross_section: CrossSectionSpec = "strip",
) -> gf.Component:
    r"""Returns polarization splitter rotator.

    "Novel concept for ultracompact polarization splitter-rotator
    based on silicon nanowires." By D. Dai, and J. E. Bowers
    (Optics express vol 19, no. 11 pp. 10940-10949 (2011)).

    Args:
        width_taper_in: Three west widths of the input tapers in um.
        length_taper_in: Two or three length of the bend regions in um.
        width_coupler: Top and bottom widths of the coupling region in um.
        length_coupler: Length of the coupling region in um.
        gap: Distance between the coupler in um.
        width_out: Width of the splitter region in um.
        length_out: Length of the splitter region in um.
        dy: Port-to-port distance between the splitter region in um.
        cross_section: cross-section spec.


    Notes:
        The length of third input taper is automatically determined
        if only two lengths are in arguments.
    """
    return _components.polarization_splitter_rotator(
        width_taper_in=width_taper_in,
        length_taper_in=length_taper_in,
        width_coupler=width_coupler,
        length_coupler=length_coupler,
        gap=gap,
        width_out=width_out,
        length_out=length_out,
        dy=dy,
        cross_section=cross_section,
    )


@gf.cell(tags=["filters"], schematic_function=terminator_schematic)
def terminator(
    length: float | None = 50,
    cross_section_input: CrossSectionSpec = _default_strip,
    cross_section_tip: CrossSectionSpec | None = None,
    tapered_width: float = 0.2,
    doping_layers: LayerSpecs = ("NPP",),
    doping_offset: float = 1.0,
) -> gf.Component:
    r"""Returns doped taper to terminate waveguides.

    Args:
        length: distance between input and narrow tapered end.
        cross_section_input: input cross-section.
        cross_section_tip: cross-section at the end of the termination.
        tapered_width: width of the default cross-section at the end of the termination.
            Only used if cross_section_tip is not None.
        doping_layers: doping layers to superimpose on the taper. Default N++.
        doping_offset: offset of the doping layer beyond the bbox
    """
    return _components.terminator(
        length=length,
        cross_section_input=cross_section_input,
        cross_section_tip=cross_section_tip,
        tapered_width=tapered_width,
        doping_layers=doping_layers,
        doping_offset=doping_offset,
    )


@gf.cell(tags=["filters"], schematic_function=terminator_schematic)
def terminator_spiral(
    separation: float = 3.0,
    width_tip: float = 0.2,
    number_of_loops: float = 1,
    npoints: int = 1000,
    min_bend_radius: float | None = None,
    cross_section: CrossSectionSpec = "strip",
) -> gf.Component:
    r"""Returns doped taper to terminate waveguides.

    Args:
        separation: separation between the loops.
        width_tip: width of the default cross-section at the end of the termination.
            Only used if cross_section_tip is not None.
        number_of_loops: number of loops in the spiral.
        npoints: points for the spiral.
        min_bend_radius: minimum bend radius for the spiral.
        cross_section: input cross-section.
    """
    return _components.terminator_spiral(
        separation=separation,
        width_tip=width_tip,
        number_of_loops=number_of_loops,
        npoints=npoints,
        min_bend_radius=min_bend_radius,
        cross_section=cross_section,
    )


__all__ = [
    "awg",
    "dbr",
    "dbr_cell",
    "dbr_tapered",
    "fiber",
    "fiber_array",
    "free_propagation_region",
    "loop_mirror",
    "mode_converter",
    "polarization_splitter_rotator",
    "terminator",
    "terminator_spiral",
]
