"""Generated functions cells.

Generated by .github/generate_cells.py. Do not edit by hand.
Run ``make cells-regen`` to regenerate, ``make cells-check`` to verify.
"""

from __future__ import annotations

import gdsfactory as gf
from gdsfactory import containers as _containers
from gdsfactory.routing.add_electrical_pads_shortest import (
    select_ports_electrical as _default_select_ports_electrical,
)
from gdsfactory.routing.add_fiber_array import (
    select_ports_optical as _default_select_ports_optical,
)
from gdsfactory.typings import *  # noqa: F403


@gf.cell
def add_electrical_pads_shortest(
    component: ComponentSpec = "wire_straight",
    pad: ComponentSpec = "pad",
    pad_port_spacing: float = 50.0,
    pad_size: Size | None = None,
    select_ports: PortsFactory = _default_select_ports_electrical,
    port_names: Strs | None = None,
    port_orientation: AngleInDegrees = 90,
    layer: LayerSpec = "M3",
) -> gf.Component:
    r"""Returns new Component with a pad by each electrical port.

    Args:
        component: to route.
        pad: pad element or function.
        pad_port_spacing: spacing between pad and port.
        pad_size: pad size.
        select_ports: function to select ports.
        port_names: optional port names. Overrides select_ports.
        port_orientation: in degrees.
        layer: for the routing.

    Example:
        ```python
        import gdsfactory as gf
        c = gf.components.cross(length=100, layer=(49, 0), port_type="electrical")
        c = gf.routing.add_electrical_pads_shortest(c, pad_port_spacing=200)
        c.plot()
        ```
    """
    return _containers.add_electrical_pads_shortest(
        component=component,
        pad=pad,
        pad_port_spacing=pad_port_spacing,
        pad_size=pad_size,
        select_ports=select_ports,
        port_names=port_names,
        port_orientation=port_orientation,
        layer=layer,
    )


@gf.cell
def add_electrical_pads_top(
    component: ComponentSpec,
    direction: Literal[top, right] = "top",
    spacing: Float2 = (0.0, 100.0),
    pad_array: ComponentSpec = "pad_array",
    select_ports: SelectPorts = _default_select_ports_electrical,
    port_names: Strs | None = None,
    layer: LayerSpec = "MTOP",
    **kwargs: Any,
) -> gf.Component:
    r"""Returns new component with electrical ports connected to top pad array.

    Args:
        component: to route.
        direction: sets direction of the array (top or right).
        spacing: component to pad spacing.
        pad_array: function for pad_array.
        select_ports: function to select electrical ports.
        port_names: optional port names. Overrides select_ports.
        layer: for the routes.
        kwargs: additional arguments.

    Keyword Args:
        ports: Dict[str, Port] a port dict {port name: port}.
        prefix: select ports with port name prefix.
        suffix: select ports with port name suffix.
        orientation: select ports with orientation in degrees.
        width: select ports with port width.
        layers_excluded: List of layers to exclude.
        port_type: select ports with port type (optical, electrical, vertical_te).
        clockwise: if True, sort ports clockwise, False: counter-clockwise.


    Example:
        ```python
        import gdsfactory as gf

        c = gf.components.wire_straight(length=200.)
        cc = gf.routing.add_electrical_pads_top(component=c, spacing=(-150, 30))
        cc.plot()
        ```
    """
    return _containers.add_electrical_pads_top(
        component=component,
        direction=direction,
        spacing=spacing,
        pad_array=pad_array,
        select_ports=select_ports,
        port_names=port_names,
        layer=layer,
        **kwargs,
    )


@gf.cell
def add_electrical_pads_top_dc(
    component: ComponentSpec,
    spacing: Float2 = (0.0, 100.0),
    pad_array: ComponentSpec = "pad_array270",
    select_ports: SelectPorts = _default_select_ports_electrical,
    port_names: Strs | None = None,
    cross_section: CrossSectionSpec = "metal_routing",
    **kwargs: Any,
) -> gf.Component:
    r"""Returns new component with electrical ports connected to top pad array.

    Args:
        component: component spec to connect to.
        spacing: component to pad spacing.
        pad_array: component factor for pad_array
        select_ports: function to select_ports.
        route_bundle_function: function to route bundle of ports.
        port_names: optional port names. Overrides select_ports.
        cross_section: cross_section for the route.
        kwargs: route settings.

    Example:
        ```python
        import gdsfactory as gf
        c = gf.components.wire_straight(length=200.)
        c = gf.routing.add_electrical_pads_top_dc(c, width=10)
        c.plot()
        ```
    """
    return _containers.add_electrical_pads_top_dc(
        component=component,
        spacing=spacing,
        pad_array=pad_array,
        select_ports=select_ports,
        port_names=port_names,
        cross_section=cross_section,
        **kwargs,
    )


@gf.cell
def add_fiber_array(
    component: ComponentSpec = "straight",
    grating_coupler: ComponentSpecOrList = "grating_coupler_te",
    gc_port_name: str = "o1",
    select_ports: PortsFactory = _default_select_ports_optical,
    cross_section: CrossSectionSpec = "strip",
    start_straight_length: float = 0,
    end_straight_length: float = 0,
    mirror_grating_coupler: bool = False,
    **kwargs: Any,
) -> gf.Component:
    r"""Returns component with south routes and grating_couplers.

    You can also use pads or other terminations instead of grating couplers.

    Args:
        component: see :func:`gdsfactory.routing.add_fiber_array.add_fiber_array` for details.
        grating_coupler: see :func:`gdsfactory.routing.add_fiber_array.add_fiber_array` for details.
        gc_port_name: see :func:`gdsfactory.routing.add_fiber_array.add_fiber_array` for details.
        select_ports: see :func:`gdsfactory.routing.add_fiber_array.add_fiber_array` for details.
        cross_section: see :func:`gdsfactory.routing.add_fiber_array.add_fiber_array` for details.
        start_straight_length: see :func:`gdsfactory.routing.add_fiber_array.add_fiber_array` for details.
        end_straight_length: see :func:`gdsfactory.routing.add_fiber_array.add_fiber_array` for details.
        mirror_grating_coupler: see :func:`gdsfactory.routing.add_fiber_array.add_fiber_array` for details.
        kwargs: see :func:`gdsfactory.routing.add_fiber_array.add_fiber_array` for details.
    """
    return _containers.add_fiber_array(
        component=component,
        grating_coupler=grating_coupler,
        gc_port_name=gc_port_name,
        select_ports=select_ports,
        cross_section=cross_section,
        start_straight_length=start_straight_length,
        end_straight_length=end_straight_length,
        mirror_grating_coupler=mirror_grating_coupler,
        **kwargs,
    )


@gf.cell
def add_fiber_single(
    component: ComponentSpec = "straight",
    grating_coupler: ComponentSpecOrList = "grating_coupler_te",
    gc_port_name: str = "o1",
    gc_port_name_fiber: str = "o2",
    select_ports: SelectPorts = _default_select_ports_optical,
    cross_section: CrossSectionSpec = "strip",
    input_port_names: Sequence[str] | None = None,
    pitch: float = 70,
    with_loopback: bool = True,
    loopback_spacing: float = 100.0,
    straight: ComponentSpec = "straight",
    mirror_grating_coupler: bool = False,
    **kwargs: Any,
) -> gf.Component:
    r"""Returns component with south routes and grating_couplers.

    You can also use pads or other terminations instead of grating couplers.

    Args:
        component: component spec to connect to grating couplers.
        grating_coupler: spec for route terminations.
        gc_port_name: grating coupler input port name.
        gc_port_name_fiber: grating coupler output port name.
        select_ports: function to select ports.
        cross_section: cross_section function.
        input_port_names: list of input port names to connect to grating couplers.
        pitch: spacing between fibers.
        with_loopback: adds loopback structures.
        loopback_spacing: spacing between loopback and test structure.
        straight: straight spec.
        mirror_grating_coupler: if True, mirrors the grating coupler.
        kwargs: additional arguments.

    Keyword Args:
        bend: bend spec.
        straight: straight spec.
        fanout_length: if None, automatic calculation of fanout length.
        max_y0_optical: in um.
        with_loopback: True, adds loopback structures.
        straight_separation: from edge to edge.
        list_port_labels: None, adds TM labels to port indices in this list.
        connected_port_list_ids: names of ports only for type 0 optical routing.
        nb_optical_ports_lines: number of grating coupler lines.
        force_manhattan: False
        excluded_ports: list of port names to exclude when adding gratings.
        grating_indices: list of grating coupler indices.
        routing_straight: function to route.
        routing_method: route_bundle.
        gc_rotation: fiber coupler rotation in degrees. Defaults to -90.
        input_port_indexes: to connect.

    Example:
        ```python
        import gdsfactory as gf

        c = gf.components.crossing()
        cc = gf.routing.add_fiber_array(
        component=c,
        grating_coupler=gf.components.grating_coupler_elliptical_te,
        with_loopback=False
        )
        cc.plot()
        ```
    """
    return _containers.add_fiber_single(
        component=component,
        grating_coupler=grating_coupler,
        gc_port_name=gc_port_name,
        gc_port_name_fiber=gc_port_name_fiber,
        select_ports=select_ports,
        cross_section=cross_section,
        input_port_names=input_port_names,
        pitch=pitch,
        with_loopback=with_loopback,
        loopback_spacing=loopback_spacing,
        straight=straight,
        mirror_grating_coupler=mirror_grating_coupler,
        **kwargs,
    )


@gf.cell
def add_padding_to_size(
    component: ComponentSpec,
    layers: LayerSpecs = ("PADDING",),
    xsize: float | None = None,
    ysize: float | None = None,
    left: float = 0,
    bottom: float = 0,
) -> gf.Component:
    r"""Returns component with padding layers on each side.

    New size is multiple of grid size.

    Args:
        component: to add padding.
        layers: list of layers.
        xsize: x size to fill up in um.
        ysize: y size to fill up in um.
        left: left padding in um to fill up in um.
        bottom: bottom padding in um to fill up in um.
    """
    return _containers.add_padding_to_size(
        component=component,
        layers=layers,
        xsize=xsize,
        ysize=ysize,
        left=left,
        bottom=bottom,
    )


@gf.cell
def add_padding_to_size_container(
    component: ComponentSpec,
    function: Callable[..., Any] | None = None,
    copy_ports: bool = True,
    **kwargs: Any,
) -> gf.Component:
    r"""Returns new component with a component reference.

    Args:
        component: to add to container.
        function: function to apply to component.
        copy_ports: if True, copies ports from component to container.
        kwargs: keyword arguments to pass to function.
    """
    return _containers.add_padding_to_size_container(
        component=component,
        function=function,
        copy_ports=copy_ports,
        **kwargs,
    )


@gf.cell
def add_pads_bot(
    component: ComponentSpec = "straight_heater_metal",
    select_ports: SelectPorts = _default_select_ports_electrical,
    port_names: Strs | None = None,
    cross_section: CrossSectionSpec = "metal_routing",
    pad_port_name: str = "e1",
    pad: ComponentSpec = "pad_rectangular",
    bend: ComponentSpec = "wire_corner",
    straight_separation: float = 15.0,
    pad_pitch: float = 100.0,
    port_type: str = "electrical",
    allow_width_mismatch: bool = True,
    fanout_length: float | None = None,
    route_width: float | None = None,
    bboxes: BoundingBoxes | None = None,
    avoid_component_bbox: bool = False,
    auto_taper: bool = True,
    **kwargs: Any,
) -> gf.Component:
    r"""Returns new component with ports connected bottom pads.

    Args:
        component: component spec to connect to.
        select_ports: function to select_ports.
        port_names: optional port names. Overrides select_ports.
        cross_section: cross_section spec.
        get_input_labels_function: function to get input labels. None skips labels.
        layer_label: optional layer for grating coupler label.
        pad_port_name: pad input port name.
        pad_port_labels: pad list of labels.
        pad: spec for route terminations.
        bend: bend spec.
        straight_separation: from wire edge to edge. Defaults to xs.width+xs.gap
        pad_pitch: in um. Defaults to pad_pitch constant from the PDK.
        port_type: port type.
        allow_width_mismatch: True
        fanout_length: if None, automatic calculation of fanout length.
        route_width: width of the route. If None, defaults to cross_section.width.
        bboxes: list bounding boxes to avoid for routing.
        avoid_component_bbox: avoid component bbox for routing.
        auto_taper: adds tapers to the routing.
        kwargs: additional arguments.

    Keyword Args:
        straight: straight spec.
        get_input_label_text_loopback_function: function to get input label test.
        get_input_label_text_function: for labels.
        max_y0_optical: in um.
        with_loopback: True, adds loopback structures.
        list_port_labels: None, adds TM labels to port indices in this list.
        connected_port_list_ids: names of ports only for type 0 optical routing.
        nb_optical_ports_lines: number of grating coupler lines.
        force_manhattan: False
        excluded_ports: list of port names to exclude when adding gratings.
        grating_indices: list of grating coupler indices.
        routing_straight: function to route.
        routing_method: route_bundle.
        gc_rotation: fiber coupler rotation in degrees. Defaults to -90.
        input_port_indexes: to connect.
        allow_width_mismatch: True

    Example:
        ```python
        import gdsfactory as gf
        c = gf.c.nxn(
        xsize=600,
        ysize=200,
        north=2,
        south=3,
        wg_width=10,
        layer="M3",
        port_type="electrical",
        )
        cc = gf.routing.add_pads_bot(component=c, port_names=("e1", "e4"), fanout_length=50)
        cc.plot()
        ```
    """
    return _containers.add_pads_bot(
        component=component,
        select_ports=select_ports,
        port_names=port_names,
        cross_section=cross_section,
        pad_port_name=pad_port_name,
        pad=pad,
        bend=bend,
        straight_separation=straight_separation,
        pad_pitch=pad_pitch,
        port_type=port_type,
        allow_width_mismatch=allow_width_mismatch,
        fanout_length=fanout_length,
        route_width=route_width,
        bboxes=bboxes,
        avoid_component_bbox=avoid_component_bbox,
        auto_taper=auto_taper,
        **kwargs,
    )


@gf.cell
def add_pads_top(
    component: ComponentSpec = "straight_heater_metal",
    select_ports: SelectPorts = _default_select_ports_electrical,
    port_names: Strs | None = None,
    cross_section: CrossSectionSpec = "metal_routing",
    pad_port_name: str = "e1",
    pad: ComponentSpec = "pad_rectangular",
    bend: ComponentSpec = "wire_corner",
    straight_separation: float = 15.0,
    pad_pitch: float = 100.0,
    port_type: str = "electrical",
    allow_width_mismatch: bool = True,
    fanout_length: float | None = None,
    route_width: float | None = 0,
    bboxes: BoundingBoxes | None = None,
    avoid_component_bbox: bool = False,
    auto_taper: bool = True,
    **kwargs: Any,
) -> gf.Component:
    r"""Returns new component with ports connected top pads.

    Args:
        component: component spec to connect to.
        select_ports: function to select_ports.
        port_names: optional port names. Overrides select_ports.
        cross_section: cross_section spec.
        get_input_labels_function: function to get input labels. None skips labels.
        layer_label: optional layer for grating coupler label.
        pad_port_name: pad input port name.
        pad_port_labels: pad list of labels.
        pad: spec for route terminations.
        bend: bend spec.
        straight_separation: from wire edge to edge. Defaults to xs.width+xs.gap
        pad_pitch: in um. Defaults to pad_pitch constant from the PDK.
        port_type: port type.
        allow_width_mismatch: True
        fanout_length: if None, automatic calculation of fanout length.
        route_width: width of the route. If None, defaults to cross_section.width.
        bboxes: list of bounding boxes to avoid.
        avoid_component_bbox: True
        auto_taper: adds tapers to the routing.
        kwargs: additional arguments.

    Keyword Args:
        straight: straight spec.
        get_input_label_text_loopback_function: function to get input label test.
        get_input_label_text_function: for labels.
        max_y0_optical: in um.
        with_loopback: True, adds loopback structures.
        list_port_labels: None, adds TM labels to port indices in this list.
        connected_port_list_ids: names of ports only for type 0 optical routing.
        nb_optical_ports_lines: number of grating coupler lines.
        force_manhattan: False
        excluded_ports: list of port names to exclude when adding gratings.
        grating_indices: list of grating coupler indices.
        routing_straight: function to route.
        routing_method: route_bundle.
        gc_rotation: fiber coupler rotation in degrees. Defaults to -90.
        input_port_indexes: to connect.
        allow_width_mismatch: True

    Example:
        ```python
        import gdsfactory as gf
        c = gf.c.nxn(
        xsize=600,
        ysize=200,
        north=2,
        south=3,
        wg_width=10,
        layer="M3",
        port_type="electrical",
        )
        cc = gf.routing.add_pads_top(component=c, port_names=("e1", "e4"), fanout_length=50)
        cc.plot()
        ```
    """
    return _containers.add_pads_top(
        component=component,
        select_ports=select_ports,
        port_names=port_names,
        cross_section=cross_section,
        pad_port_name=pad_port_name,
        pad=pad,
        bend=bend,
        straight_separation=straight_separation,
        pad_pitch=pad_pitch,
        port_type=port_type,
        allow_width_mismatch=allow_width_mismatch,
        fanout_length=fanout_length,
        route_width=route_width,
        bboxes=bboxes,
        avoid_component_bbox=avoid_component_bbox,
        auto_taper=auto_taper,
        **kwargs,
    )


@gf.cell
def extract(
    component: Component,
    layers: LayerSpecs,
    recursive: bool = True,
) -> gf.Component:
    r"""Extracts a list of layers and adds them to a new Component.

    Args:
        component: to extract the layers from.
        layers: list of layers to extract.
        recursive: if True, extracts the shapes recursively.
    """
    return _containers.extract(
        component=component,
        layers=layers,
        recursive=recursive,
    )


@gf.cell
def fanout2x2(
    component: ComponentSpec = "mmi2x2",
    port_spacing: float = 20.0,
    bend_length: float | None = None,
    npoints: int = 101,
    select_ports: PortsFactory = _default_select_ports_optical,
    cross_section: CrossSectionSpec = "strip",
    port1: str = "o1",
    port2: str = "o2",
    port3: str = "o3",
    port4: str = "o4",
    **kwargs: Any,
) -> gf.Component:
    r"""Returns component with Sbend fanout routes.

    Args:
        component: to fanout.
        port_spacing: for the returned component.
        bend_length: length of the bend (defaults to port_spacing).
        npoints: for sbend.
        select_ports: function to select  optical_ports ports.
        cross_section: cross_section spec.
        port1: bottom west port.
        port2: top west port.
        port3: top east port.
        port4: bottom east port.
        kwargs: cross_section settings.

    Example:
        ```python
        import gdsfactory as gf
        c = gf.components.nxn(west=2, east=2)

        cc = gf.routing.fanout2x2(component=c, port_spacing=20)
        cc.plot()
        ```
    """
    return _containers.fanout2x2(
        component=component,
        port_spacing=port_spacing,
        bend_length=bend_length,
        npoints=npoints,
        select_ports=select_ports,
        cross_section=cross_section,
        port1=port1,
        port2=port2,
        port3=port3,
        port4=port4,
        **kwargs,
    )


@gf.cell
def move_port_to_zero(
    component: Component,
    port_name: str = "o1",
    mirror: bool = False,
) -> gf.Component:
    r"""Return a container that contains a reference to the original component.

    The new component has port_name in (0, 0).

    Args:
        component: to move the port to (0, 0).
        port_name: to move to (0, 0).
        mirror: if True, mirrors the component.
    """
    return _containers.move_port_to_zero(
        component=component,
        port_name=port_name,
        mirror=mirror,
    )


@gf.cell
def rotate180(
    component: Component,
    angle: float = 180,
) -> gf.Component:
    r"""Rotate a component by an angle in degrees.

    Args:
        component: to rotate.
        angle: in increments of 90°.

    Returns: Rotated component.
    """
    return _containers.rotate180(
        component=component,
        angle=angle,
    )


@gf.cell
def rotate270(
    component: Component,
    angle: float = 270,
) -> gf.Component:
    r"""Rotate a component by an angle in degrees.

    Args:
        component: to rotate.
        angle: in increments of 90°.

    Returns: Rotated component.
    """
    return _containers.rotate270(
        component=component,
        angle=angle,
    )


@gf.cell
def rotate90(
    component: Component,
    angle: float = 90,
) -> gf.Component:
    r"""Rotate a component by an angle in degrees.

    Args:
        component: to rotate.
        angle: in increments of 90°.

    Returns: Rotated component.
    """
    return _containers.rotate90(
        component=component,
        angle=angle,
    )


@gf.cell
def trim(
    component: Component,
    domain: Sequence[tuple[float, float]],
    flatten: bool = False,
) -> gf.Component:
    r"""Trim a component by another geometry, preserving the component's layers and ports.

    Useful to get a smaller component from a larger one for simulation.

    Args:
        component: Component(/Reference).
        domain: list of array-like[N][2] representing the boundary of the component to keep.
        flatten: if True, flattens the component.

    Returns: New component with layers (and possibly ports) of the component restricted to the domain.

    Example:
        ```python
        import gdsfactory as gf
        c = gf.components.straight_pin(length=10)
        trimmed_c = gf.functions.trim(component=c, domain=[[0, -5], [0, 5], [5, 5], [5, -5]])
        trimmed_c.plot()
        ```
    """
    return _containers.trim(
        component=component,
        domain=domain,
        flatten=flatten,
    )


__all__ = [
    "add_electrical_pads_shortest",
    "add_electrical_pads_top",
    "add_electrical_pads_top_dc",
    "add_fiber_array",
    "add_fiber_single",
    "add_padding_to_size",
    "add_padding_to_size_container",
    "add_pads_bot",
    "add_pads_top",
    "extract",
    "fanout2x2",
    "move_port_to_zero",
    "rotate180",
    "rotate270",
    "rotate90",
    "trim",
]
