"""Generated grating_couplers cells.

Generated by .github/generate_cells.py. Do not edit by hand.
Run ``make cells-regen`` to regenerate, ``make cells-check`` to verify.
"""

from __future__ import annotations

import gdsfactory as gf

# ruff: noqa: B006
from gdsfactory import components as _components
from gdsfactory.components.grating_couplers.grating_coupler_dual_pol import (
    _unit_cell as _default__unit_cell,
)
from gdsfactory.typings import *  # noqa: F403

from gpdk.cells._schematic import (
    grating_coupler_schematic,
)


@gf.cell(tags=["grating_couplers"])
def grating_coupler_array(
    grating_coupler: ComponentSpec = "grating_coupler_elliptical",
    pitch: float = 127.0,
    n: int = 6,
    port_name: str = "o1",
    rotation: int = -90,
    with_loopback: bool = False,
    cross_section: CrossSectionSpec = "strip",
    straight_to_grating_spacing: float = 10.0,
    centered: bool = True,
    radius: float | None = None,
    bend: ComponentSpec = "bend_euler",
    mirror_grating_coupler: bool = False,
) -> gf.Component:
    r"""Array of grating couplers.

    Args:
        grating_coupler: ComponentSpec.
        pitch: x spacing.
        n: number of grating couplers.
        port_name: port name.
        rotation: rotation angle for each reference.
        with_loopback: if True, adds a loopback between edge GCs. Only works for rotation = 90 for now.
        cross_section: cross_section for the routing.
        straight_to_grating_spacing: spacing between the last grating coupler and the loopback.
        centered: if True, centers the array around the origin.
        radius: optional radius for routing the loopback.
        bend: ComponentSpec for the bend used in the loopback.
        mirror_grating_coupler: if True, mirrors the grating coupler.
    """
    return _components.grating_coupler_array(
        grating_coupler=grating_coupler,
        pitch=pitch,
        n=n,
        port_name=port_name,
        rotation=rotation,
        with_loopback=with_loopback,
        cross_section=cross_section,
        straight_to_grating_spacing=straight_to_grating_spacing,
        centered=centered,
        radius=radius,
        bend=bend,
        mirror_grating_coupler=mirror_grating_coupler,
    )


@gf.cell(tags=["grating_couplers"], schematic_function=grating_coupler_schematic)
def grating_coupler_dual_pol(
    unit_cell: ComponentSpec = _default__unit_cell,
    period_x: float = 0.58,
    period_y: float = 0.58,
    x_span: float = 11,
    y_span: float = 11,
    length_taper: float = 150.0,
    width_taper: float = 10.0,
    polarization: str = "te",
    wavelength: float = 1.55,
    taper: ComponentSpec = "taper",
    base_layer: LayerSpec = "WG",
    cross_section: CrossSectionSpec = "strip",
) -> gf.Component:
    r"""2 dimensional, dual polarization grating coupler.

    Based on a photonic crystal with a unit cell that is usually an ellipse,
    a rectangle or a circle.
    The default values are loosely based on Taillaert et al,
    "A Compact Two-Dimensional Grating Coupler Used as a Polarization Splitter",
    IEEE Phot. Techn. Lett. 15(9), 2003.

    Args:
        unit_cell: component describing the unit cell of the photonic crystal.
        period_x: spacing between unit cells in the x direction [um].
        period_y: spacing between unit cells in the y direction [um].
        x_span: full x span of the photonic crystal.
        y_span: full y span of the photonic crystal.
        length_taper: taper length [um].
        width_taper: width of the taper at the grating coupler side [um].
        polarization: polarization of the grating coupler.
        wavelength: operation wavelength [um]
        taper: function to generate the tapers.
        base_layer: layer to draw over the whole photonic crystal
            (necessary if the unit cells are etched into a base layer).
        cross_section: for the routing waveguides.

        side view
                      fiber

                   /  /  /  /
                  /  /  /  /

                _|-|_|-|_|-|___  --> unit_cells
                   base_layer |
            o1  ______________|


        top view

                   -------------
               // | o   o   o  |
        o1 __ //  | o   o   o  |
              \\  | o   o   o  |
               \\ | o   o   o  |
                   -------------
                   \\         //
                    \\       //
                         |
                         o2
    """
    return _components.grating_coupler_dual_pol(
        unit_cell=unit_cell,
        period_x=period_x,
        period_y=period_y,
        x_span=x_span,
        y_span=y_span,
        length_taper=length_taper,
        width_taper=width_taper,
        polarization=polarization,
        wavelength=wavelength,
        taper=taper,
        base_layer=base_layer,
        cross_section=cross_section,
    )


@gf.cell(tags=["grating_couplers"], schematic_function=grating_coupler_schematic)
def grating_coupler_elliptical(
    polarization: str = "te",
    taper_length: float = 16.6,
    taper_angle: float = 40.0,
    wavelength: float = 1.554,
    fiber_angle: float = 15.0,
    grating_line_width: float = 0.343,
    neff: float = 2.638,
    nclad: float = 1.443,
    n_periods: int = 30,
    big_last_tooth: bool = False,
    layer_slab: LayerSpec | None = "SLAB150",
    slab_xmin: float = -1.0,
    slab_offset: float = 2.0,
    spiked: bool = True,
    cross_section: CrossSectionSpec = "strip",
) -> gf.Component:
    r"""Grating coupler with parametrization based on Lumerical FDTD simulation.

    Args:
        polarization: te or tm.
        taper_length: taper length from input.
        taper_angle: grating flare angle.
        wavelength: grating transmission central wavelength (um).
        fiber_angle: fibre angle in degrees determines ellipticity.
        grating_line_width: in um.
        neff: tooth effective index.
        nclad: cladding effective index.
        n_periods: number of periods.
        big_last_tooth: adds a big_last_tooth.
        layer_slab: layer that protects the slab under the grating.
        slab_xmin: where 0 is at the start of the taper.
        slab_offset: in um.
        spiked: grating teeth have sharp spikes to avoid non-manhattan drc errors.
        cross_section: specification (CrossSection, string or dict).

                      fiber

                   /  /  /  /
                  /  /  /  /

                _|-|_|-|_|-|___ layer
                   layer_slab |
            o1  ______________|
    """
    return _components.grating_coupler_elliptical(
        polarization=polarization,
        taper_length=taper_length,
        taper_angle=taper_angle,
        wavelength=wavelength,
        fiber_angle=fiber_angle,
        grating_line_width=grating_line_width,
        neff=neff,
        nclad=nclad,
        n_periods=n_periods,
        big_last_tooth=big_last_tooth,
        layer_slab=layer_slab,
        slab_xmin=slab_xmin,
        slab_offset=slab_offset,
        spiked=spiked,
        cross_section=cross_section,
    )


@gf.cell(tags=["grating_couplers"], schematic_function=grating_coupler_schematic)
def grating_coupler_elliptical_arbitrary(
    gaps: Floats = (0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1),
    widths: Floats = (0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5),
    taper_length: float = 16.6,
    taper_angle: float = 60.0,
    wavelength: float = 1.554,
    fiber_angle: float = 15.0,
    nclad: float = 1.443,
    layer_slab: LayerSpec | None = "SLAB150",
    layer_grating: LayerSpec | None = None,
    taper_to_slab_offset: float = -3.0,
    polarization: str = "te",
    spiked: bool = True,
    bias_gap: float = 0,
    cross_section: CrossSectionSpec = "strip",
) -> gf.Component:
    r"""Grating coupler with parametrization based on Lumerical FDTD simulation.

    The ellipticity is derived from Lumerical knowledge base
    it depends on fiber_angle (degrees), neff, and nclad

    Args:
        gaps: list of gaps.
        widths: list of widths.
        taper_length: taper length from input.
        taper_angle: grating flare angle.
        wavelength: grating transmission central wavelength (um).
        fiber_angle: fibre angle in degrees determines ellipticity.
        nclad: cladding effective index to compute ellipticity.
        layer_slab: Optional slab.
        layer_grating: Optional layer for grating.
            by default None uses cross_section.layer.
            if different from cross_section.layer expands taper.
        taper_to_slab_offset: 0 is where taper ends.
        polarization: te or tm.
        spiked: grating teeth have spikes to avoid drc errors.
        bias_gap: etch gap (um).
            Positive bias increases gap and reduces width to keep period constant.
        cross_section: cross_section spec for waveguide port.

    https://en.wikipedia.org/wiki/Ellipse
    c = (a1 ** 2 - b1 ** 2) ** 0.5
    e = (1 - (b1 / a1) ** 2) ** 0.5
    print(e)

                      fiber

                   /  /  /  /
                  /  /  /  /

                _|-|_|-|_|-|___ layer
                   layer_slab |
            o1  ______________|
    """
    return _components.grating_coupler_elliptical_arbitrary(
        gaps=gaps,
        widths=widths,
        taper_length=taper_length,
        taper_angle=taper_angle,
        wavelength=wavelength,
        fiber_angle=fiber_angle,
        nclad=nclad,
        layer_slab=layer_slab,
        layer_grating=layer_grating,
        taper_to_slab_offset=taper_to_slab_offset,
        polarization=polarization,
        spiked=spiked,
        bias_gap=bias_gap,
        cross_section=cross_section,
    )


@gf.cell(tags=["grating_couplers"], schematic_function=grating_coupler_schematic)
def grating_coupler_elliptical_lumerical(
    parameters: Floats = (
        -2.4298362615732447,
        0.1,
        0.48007023217536954,
        0.1,
        0.607397685752365,
        0.1,
        0.4498844003086115,
        0.1,
        0.4274116312627637,
        0.1,
        0.4757904248387285,
        0.1,
        0.5026649898504233,
        0.10002922416240886,
        0.5100366774007897,
        0.1,
        0.494399635363353,
        0.1079599958465788,
        0.47400592737426483,
        0.14972685326277918,
        0.43272750134545823,
        0.1839530796530385,
        0.3872023336708212,
        0.2360175325711591,
        0.36032212454768675,
        0.24261846353500535,
        0.35770350120764394,
        0.2606637836858316,
        0.3526104381544335,
        0.24668202254540886,
        0.3717488388788273,
        0.22920754299702897,
        0.37769616507688464,
        0.2246528336925301,
        0.3765437598650894,
        0.22041773376471022,
        0.38047596041838994,
        0.21923601658169187,
        0.3798873698864591,
        0.21700438236445285,
        0.38291698672245644,
        0.21827768053295463,
        0.3641322152037017,
        0.23729077006065105,
        0.3676834419346081,
        0.24865079519725933,
        0.34415050295044936,
        0.2733570818755685,
        0.3306230780901629,
        0.27350446437732157,
    ),
    layer_slab: LayerSpec | None = "SLAB150",
    taper_angle: float = 55,
    taper_length: float = 12.6,
    fiber_angle: float = 5,
    info: dict[str, Any] | None = None,
    bias_gap: float = 0,
    cross_section: CrossSectionSpec = "strip",
) -> gf.Component:
    r"""Returns a grating coupler from lumerical inverse design 3D optimization.

    this is a wrapper of components.grating_coupler_elliptical_arbitrary
    https://support.lumerical.com/hc/en-us/articles/1500000306621
    https://support.lumerical.com/hc/en-us/articles/360042800573

    Here are the simulation settings used in lumerical

        n_bg=1.44401 #Refractive index of the background material (cladding)
        wg=3.47668   # Refractive index of the waveguide material (core)
        lambda0=1550e-9
        bandwidth = 0e-9
        polarization = 'TE'
        wg_width=500e-9 # Waveguide width
        wg_height=220e-9 # Waveguide height
        etch_depth=80e-9 # etch depth
        theta_fib_mat = 5 # Angle of the fiber mode in material
        theta_taper=30
        efficiency=0.55 # 5.2 dB

    Args:
        parameters: see :func:`gdsfactory.components.grating_couplers.grating_coupler_elliptical_lumerical.grating_coupler_elliptical_lumerical` for details.
        layer_slab: see :func:`gdsfactory.components.grating_couplers.grating_coupler_elliptical_lumerical.grating_coupler_elliptical_lumerical` for details.
        taper_angle: see :func:`gdsfactory.components.grating_couplers.grating_coupler_elliptical_lumerical.grating_coupler_elliptical_lumerical` for details.
        taper_length: see :func:`gdsfactory.components.grating_couplers.grating_coupler_elliptical_lumerical.grating_coupler_elliptical_lumerical` for details.
        fiber_angle: see :func:`gdsfactory.components.grating_couplers.grating_coupler_elliptical_lumerical.grating_coupler_elliptical_lumerical` for details.
        info: see :func:`gdsfactory.components.grating_couplers.grating_coupler_elliptical_lumerical.grating_coupler_elliptical_lumerical` for details.
        bias_gap: see :func:`gdsfactory.components.grating_couplers.grating_coupler_elliptical_lumerical.grating_coupler_elliptical_lumerical` for details.
        cross_section: see :func:`gdsfactory.components.grating_couplers.grating_coupler_elliptical_lumerical.grating_coupler_elliptical_lumerical` for details.
    """
    return _components.grating_coupler_elliptical_lumerical(
        parameters=parameters,
        layer_slab=layer_slab,
        taper_angle=taper_angle,
        taper_length=taper_length,
        fiber_angle=fiber_angle,
        info=info,
        bias_gap=bias_gap,
        cross_section=cross_section,
    )


@gf.cell(tags=["grating_couplers"], schematic_function=grating_coupler_schematic)
def grating_coupler_elliptical_lumerical_etch70(
    parameters: Floats = (
        -2.4298362615732447,
        0.1,
        0.48007023217536954,
        0.1,
        0.607397685752365,
        0.1,
        0.4498844003086115,
        0.1,
        0.4274116312627637,
        0.1,
        0.4757904248387285,
        0.1,
        0.5026649898504233,
        0.10002922416240886,
        0.5100366774007897,
        0.1,
        0.494399635363353,
        0.1079599958465788,
        0.47400592737426483,
        0.14972685326277918,
        0.43272750134545823,
        0.1839530796530385,
        0.3872023336708212,
        0.2360175325711591,
        0.36032212454768675,
        0.24261846353500535,
        0.35770350120764394,
        0.2606637836858316,
        0.3526104381544335,
        0.24668202254540886,
        0.3717488388788273,
        0.22920754299702897,
        0.37769616507688464,
        0.2246528336925301,
        0.3765437598650894,
        0.22041773376471022,
        0.38047596041838994,
        0.21923601658169187,
        0.3798873698864591,
        0.21700438236445285,
        0.38291698672245644,
        0.21827768053295463,
        0.3641322152037017,
        0.23729077006065105,
        0.3676834419346081,
        0.24865079519725933,
        0.34415050295044936,
        0.2733570818755685,
        0.3306230780901629,
        0.27350446437732157,
    ),
    layer_slab: LayerSpec | None = "SLAB150",
    taper_angle: float = 55,
    taper_length: float = 12.6,
    fiber_angle: float = 5,
    info: dict[str, Any] | None = {
        "etch_depth": 0.08,
        "link": "https://support.lumerical.com/hc/en-us/articles/1500000306621",
        "fiber_angle": 5,
        "width_min": 0.1,
        "gap_min": 0.1,
        "efficiency": 0.55,
    },
    bias_gap: float = 0,
    cross_section: CrossSectionSpec = "strip",
) -> gf.Component:
    r"""Returns a grating coupler from lumerical inverse design 3D optimization.

    this is a wrapper of components.grating_coupler_elliptical_arbitrary
    https://support.lumerical.com/hc/en-us/articles/1500000306621
    https://support.lumerical.com/hc/en-us/articles/360042800573

    Here are the simulation settings used in lumerical

        n_bg=1.44401 #Refractive index of the background material (cladding)
        wg=3.47668   # Refractive index of the waveguide material (core)
        lambda0=1550e-9
        bandwidth = 0e-9
        polarization = 'TE'
        wg_width=500e-9 # Waveguide width
        wg_height=220e-9 # Waveguide height
        etch_depth=80e-9 # etch depth
        theta_fib_mat = 5 # Angle of the fiber mode in material
        theta_taper=30
        efficiency=0.55 # 5.2 dB

    Args:
        parameters: see :func:`gdsfactory.components.grating_couplers.grating_coupler_elliptical_lumerical.grating_coupler_elliptical_lumerical` for details.
        layer_slab: see :func:`gdsfactory.components.grating_couplers.grating_coupler_elliptical_lumerical.grating_coupler_elliptical_lumerical` for details.
        taper_angle: see :func:`gdsfactory.components.grating_couplers.grating_coupler_elliptical_lumerical.grating_coupler_elliptical_lumerical` for details.
        taper_length: see :func:`gdsfactory.components.grating_couplers.grating_coupler_elliptical_lumerical.grating_coupler_elliptical_lumerical` for details.
        fiber_angle: see :func:`gdsfactory.components.grating_couplers.grating_coupler_elliptical_lumerical.grating_coupler_elliptical_lumerical` for details.
        info: see :func:`gdsfactory.components.grating_couplers.grating_coupler_elliptical_lumerical.grating_coupler_elliptical_lumerical` for details.
        bias_gap: see :func:`gdsfactory.components.grating_couplers.grating_coupler_elliptical_lumerical.grating_coupler_elliptical_lumerical` for details.
        cross_section: see :func:`gdsfactory.components.grating_couplers.grating_coupler_elliptical_lumerical.grating_coupler_elliptical_lumerical` for details.
    """
    return _components.grating_coupler_elliptical_lumerical_etch70(
        parameters=parameters,
        layer_slab=layer_slab,
        taper_angle=taper_angle,
        taper_length=taper_length,
        fiber_angle=fiber_angle,
        info=info,
        bias_gap=bias_gap,
        cross_section=cross_section,
    )


@gf.cell(tags=["grating_couplers"], schematic_function=grating_coupler_schematic)
def grating_coupler_elliptical_te(
    polarization: str = "te",
    taper_length: float = 16.6,
    taper_angle: float = 40.0,
    wavelength: float = 1.554,
    fiber_angle: float = 15.0,
    grating_line_width: float = 0.343,
    neff: float = 2.638,
    nclad: float = 1.443,
    n_periods: int = 30,
    big_last_tooth: bool = False,
    layer_slab: LayerSpec | None = "SLAB150",
    slab_xmin: float = -1.0,
    slab_offset: float = 2.0,
    spiked: bool = True,
    cross_section: CrossSectionSpec = "strip",
) -> gf.Component:
    r"""Grating coupler with parametrization based on Lumerical FDTD simulation.

    Args:
        polarization: te or tm.
        taper_length: taper length from input.
        taper_angle: grating flare angle.
        wavelength: grating transmission central wavelength (um).
        fiber_angle: fibre angle in degrees determines ellipticity.
        grating_line_width: in um.
        neff: tooth effective index.
        nclad: cladding effective index.
        n_periods: number of periods.
        big_last_tooth: adds a big_last_tooth.
        layer_slab: layer that protects the slab under the grating.
        slab_xmin: where 0 is at the start of the taper.
        slab_offset: in um.
        spiked: grating teeth have sharp spikes to avoid non-manhattan drc errors.
        cross_section: specification (CrossSection, string or dict).

                      fiber

                   /  /  /  /
                  /  /  /  /

                _|-|_|-|_|-|___ layer
                   layer_slab |
            o1  ______________|
    """
    return _components.grating_coupler_elliptical_te(
        polarization=polarization,
        taper_length=taper_length,
        taper_angle=taper_angle,
        wavelength=wavelength,
        fiber_angle=fiber_angle,
        grating_line_width=grating_line_width,
        neff=neff,
        nclad=nclad,
        n_periods=n_periods,
        big_last_tooth=big_last_tooth,
        layer_slab=layer_slab,
        slab_xmin=slab_xmin,
        slab_offset=slab_offset,
        spiked=spiked,
        cross_section=cross_section,
    )


@gf.cell(tags=["grating_couplers"], schematic_function=grating_coupler_schematic)
def grating_coupler_elliptical_tm(
    polarization: str = "tm",
    taper_length: float = 30,
    taper_angle: float = 40.0,
    wavelength: float = 1.554,
    fiber_angle: float = 15.0,
    grating_line_width: float = 0.707,
    neff: float = 1.8,
    nclad: float = 1.443,
    n_periods: int = 16,
    big_last_tooth: bool = False,
    layer_slab: LayerSpec | None = "SLAB150",
    slab_xmin: float = -2,
    slab_offset: float = 2.0,
    spiked: bool = True,
    cross_section: CrossSectionSpec = "strip",
) -> gf.Component:
    r"""Grating coupler with parametrization based on Lumerical FDTD simulation.

    Args:
        polarization: te or tm.
        taper_length: taper length from input.
        taper_angle: grating flare angle.
        wavelength: grating transmission central wavelength (um).
        fiber_angle: fibre angle in degrees determines ellipticity.
        grating_line_width: in um.
        neff: tooth effective index.
        nclad: cladding effective index.
        n_periods: number of periods.
        big_last_tooth: adds a big_last_tooth.
        layer_slab: layer that protects the slab under the grating.
        slab_xmin: where 0 is at the start of the taper.
        slab_offset: in um.
        spiked: grating teeth have sharp spikes to avoid non-manhattan drc errors.
        cross_section: specification (CrossSection, string or dict).

                      fiber

                   /  /  /  /
                  /  /  /  /

                _|-|_|-|_|-|___ layer
                   layer_slab |
            o1  ______________|
    """
    return _components.grating_coupler_elliptical_tm(
        polarization=polarization,
        taper_length=taper_length,
        taper_angle=taper_angle,
        wavelength=wavelength,
        fiber_angle=fiber_angle,
        grating_line_width=grating_line_width,
        neff=neff,
        nclad=nclad,
        n_periods=n_periods,
        big_last_tooth=big_last_tooth,
        layer_slab=layer_slab,
        slab_xmin=slab_xmin,
        slab_offset=slab_offset,
        spiked=spiked,
        cross_section=cross_section,
    )


@gf.cell(tags=["grating_couplers"], schematic_function=grating_coupler_schematic)
def grating_coupler_elliptical_trenches(
    polarization: str = "te",
    taper_length: float = 16.6,
    taper_angle: float = 30.0,
    trenches_extra_angle: float = 9.0,
    wavelength: float = 1.53,
    fiber_angle: float = 15.0,
    grating_line_width: float = 0.343,
    neff: float = 2.638,
    ncladding: float = 1.443,
    layer_trench: LayerSpec = "SHALLOW_ETCH",
    p_start: int = 26,
    n_periods: int = 30,
    end_straight_length: float = 0.2,
    taper: ComponentSpec = "taper",
    cross_section: CrossSectionSpec = "strip",
) -> gf.Component:
    r"""Returns Grating coupler with defined trenches.

    Some foundries define the grating coupler by a shallow etch step (trenches)
    Others define the slab that they keep (see grating_coupler_elliptical)

    Args:
        polarization: 'te' or 'tm'.
        taper_length: taper length from straight I/O.
        taper_angle: grating flare angle.
        trenches_extra_angle: extra angle for the trenches.
        wavelength: grating transmission central wavelength.
        fiber_angle: fibre polish angle in degrees.
        grating_line_width: of the 220 ridge.
        neff: tooth effective index.
        ncladding: cladding index.
        layer_trench: for the trench.
        p_start: first tooth.
        n_periods: number of grating teeth.
        end_straight_length: at the end of straight.
        taper: taper function.
        cross_section: cross_section spec.

                      fiber

                   /  /  /  /
                  /  /  /  /
                _|-|_|-|_|-|___
        WG  o1  ______________|
    """
    return _components.grating_coupler_elliptical_trenches(
        polarization=polarization,
        taper_length=taper_length,
        taper_angle=taper_angle,
        trenches_extra_angle=trenches_extra_angle,
        wavelength=wavelength,
        fiber_angle=fiber_angle,
        grating_line_width=grating_line_width,
        neff=neff,
        ncladding=ncladding,
        layer_trench=layer_trench,
        p_start=p_start,
        n_periods=n_periods,
        end_straight_length=end_straight_length,
        taper=taper,
        cross_section=cross_section,
    )


@gf.cell(tags=["grating_couplers"], schematic_function=grating_coupler_schematic)
def grating_coupler_elliptical_uniform(
    n_periods: int = 20,
    period: float = 0.75,
    fill_factor: float = 0.5,
    **kwargs: Any,
) -> gf.Component:
    r"""Grating coupler with parametrization based on Lumerical FDTD simulation.

    The ellipticity is derived from Lumerical knowledge base
    it depends on fiber_angle (degrees), neff, and nclad

    Args:
        n_periods: number of grating periods.
        period: grating pitch in um.
        fill_factor: ratio of grating width vs gap.

    Keyword Args:
        taper_length: taper length from input.
        taper_angle: grating flare angle.
        wavelength: grating transmission central wavelength (um).
        fiber_angle: fibre angle in degrees determines ellipticity.
        neff: tooth effective index to compute ellipticity.
        nclad: cladding effective index to compute ellipticity.
        layer_slab: Optional slab.
        taper_to_slab_offset: where 0 is at the start of the taper.
        polarization: te or tm.
        spiked: grating teeth have spikes to avoid drc errors..
        bias_gap: etch gap (um).
            Positive bias increases gap and reduces width to keep period constant.
        cross_section: cross_section spec for waveguide port.
        kwargs: cross_section settings.

                      fiber

                   /  /  /  /
                  /  /  /  /

                _|-|_|-|_|-|___ layer
                   layer_slab |
            o1  ______________|
    """
    return _components.grating_coupler_elliptical_uniform(
        n_periods=n_periods,
        period=period,
        fill_factor=fill_factor,
        **kwargs,
    )


@gf.cell(tags=["grating_couplers"])
def grating_coupler_loss(
    pitch: float = 127.0,
    grating_coupler: ComponentSpec = "grating_coupler_elliptical_trenches",
    cross_section: CrossSectionSpec = "strip",
    port_name: str = "o1",
    rotation: float = -90,
    nfibers: int = 10,
    grating_coupler_spacing: float = 5.0,
) -> gf.Component:
    r"""Grating coupler test structure for de-embeding fiber array.

    Connects channel 1->3, 1->5 ... 1->nfibers with grating couplers.

    Only odd channels are connected to the grating couplers as even channels in the align_tree.

    Args:
        pitch: um.
        grating_coupler: spec.
        cross_section: spec.
        port_name: for the grating_coupler port.
        rotation: degrees.
        nfibers: number of fibers to connect.
        grating_coupler_spacing: um.
    """
    return _components.grating_coupler_loss(
        pitch=pitch,
        grating_coupler=grating_coupler,
        cross_section=cross_section,
        port_name=port_name,
        rotation=rotation,
        nfibers=nfibers,
        grating_coupler_spacing=grating_coupler_spacing,
    )


@gf.cell(tags=["grating_couplers"], schematic_function=grating_coupler_schematic)
def grating_coupler_rectangular(
    n_periods: int = 20,
    period: float = 0.75,
    fill_factor: float = 0.5,
    width_grating: float = 11.0,
    length_taper: float = 150.0,
    polarization: str = "te",
    wavelength: float = 1.55,
    taper: ComponentSpec = "taper",
    layer_slab: LayerSpec | None = "SLAB150",
    layer_grating: LayerSpec | None = None,
    fiber_angle: float = 15,
    slab_xmin: float = -1.0,
    slab_offset: float = 1.0,
    cross_section: CrossSectionSpec = "strip",
) -> gf.Component:
    r"""Grating coupler with rectangular shapes (not elliptical).

    Needs longer taper than elliptical.
    Grating teeth are straight.
    For a focusing grating take a look at grating_coupler_elliptical.

    Args:
        n_periods: number of grating teeth.
        period: grating pitch.
        fill_factor: ratio of grating width vs gap.
        width_grating: 11.
        length_taper: 150.
        polarization: 'te' or 'tm'.
        wavelength: in um.
        taper: function.
        layer_slab: layer that protects the slab under the grating.
        layer_grating: layer for the grating.
        fiber_angle: in degrees.
        slab_xmin: where 0 is at the start of the taper.
        slab_offset: from edge of grating to edge of the slab.
        cross_section: for input waveguide port.

        side view
                      fiber

                   /  /  /  /
                  /  /  /  /

                _|-|_|-|_|-|___ layer
                   layer_slab |
            o1  ______________|


        top view     _________
                    /| | | | |
                   / | | | | |
                  /taper_angle
                 /_ _| | | | |
        wg_width |   | | | | |
                 \   | | | | |
                  \  | | | | |
                   \ | | | | |
                    \|_|_|_|_|
                 <-->
                taper_length
    """
    return _components.grating_coupler_rectangular(
        n_periods=n_periods,
        period=period,
        fill_factor=fill_factor,
        width_grating=width_grating,
        length_taper=length_taper,
        polarization=polarization,
        wavelength=wavelength,
        taper=taper,
        layer_slab=layer_slab,
        layer_grating=layer_grating,
        fiber_angle=fiber_angle,
        slab_xmin=slab_xmin,
        slab_offset=slab_offset,
        cross_section=cross_section,
    )


@gf.cell(tags=["grating_couplers"], schematic_function=grating_coupler_schematic)
def grating_coupler_rectangular_arbitrary(
    gaps: Floats = (0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2),
    widths: Floats = (0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5),
    width_grating: float = 11.0,
    length_taper: float = 150.0,
    polarization: str = "te",
    wavelength: float = 1.55,
    layer_grating: LayerSpec | None = None,
    layer_slab: LayerSpec | None = None,
    slab_xmin: float = -1.0,
    slab_offset: float = 1.0,
    fiber_angle: float = 15,
    cross_section: CrossSectionSpec = "strip",
) -> gf.Component:
    r"""Grating coupler uniform with rectangular shape (not elliptical).

    Therefore it needs a longer taper.
    Grating teeth are straight instead of elliptical.

    Args:
        gaps: list of gaps between grating teeth.
        widths: list of grating widths.
        width_grating: grating teeth width.
        length_taper: taper length (um).
        polarization: 'te' or 'tm'.
        wavelength: in um.
        layer_grating: Optional layer for grating. \
                by default None uses cross_section.layer. \
                if different from cross_section.layer expands taper.
        layer_slab: layer that protects the slab under the grating.
        slab_xmin: where 0 is at the start of the taper.
        slab_offset: from edge of grating to edge of the slab.
        fiber_angle: in degrees.
        cross_section: for input waveguide port.

                      fiber

                   /  /  /  /
                  /  /  /  /

                _|-|_|-|_|-|___ layer
                   layer_slab |
            o1  ______________|



        top view     _________
                    /| | | | |
                   / | | | | |
                  /taper_angle
                 /_ _| | | | |
        wg_width |   | | | | |
                 \   | | | | |
                  \  | | | | |
                   \ | | | | |
                    \|_|_|_|_|
                 <-->
                taper_length
    """
    return _components.grating_coupler_rectangular_arbitrary(
        gaps=gaps,
        widths=widths,
        width_grating=width_grating,
        length_taper=length_taper,
        polarization=polarization,
        wavelength=wavelength,
        layer_grating=layer_grating,
        layer_slab=layer_slab,
        slab_xmin=slab_xmin,
        slab_offset=slab_offset,
        fiber_angle=fiber_angle,
        cross_section=cross_section,
    )


@gf.cell(tags=["grating_couplers"], schematic_function=grating_coupler_schematic)
def grating_coupler_te(
    polarization: str = "te",
    taper_length: float = 16.6,
    taper_angle: float = 35,
    trenches_extra_angle: float = 9.0,
    wavelength: float = 1.53,
    fiber_angle: float = 15.0,
    grating_line_width: float = 0.343,
    neff: float = 2.638,
    ncladding: float = 1.443,
    layer_trench: LayerSpec = "SHALLOW_ETCH",
    p_start: int = 26,
    n_periods: int = 30,
    end_straight_length: float = 0.2,
    taper: ComponentSpec = "taper",
    cross_section: CrossSectionSpec = "strip",
) -> gf.Component:
    r"""Returns Grating coupler with defined trenches.

    Some foundries define the grating coupler by a shallow etch step (trenches)
    Others define the slab that they keep (see grating_coupler_elliptical)

    Args:
        polarization: 'te' or 'tm'.
        taper_length: taper length from straight I/O.
        taper_angle: grating flare angle.
        trenches_extra_angle: extra angle for the trenches.
        wavelength: grating transmission central wavelength.
        fiber_angle: fibre polish angle in degrees.
        grating_line_width: of the 220 ridge.
        neff: tooth effective index.
        ncladding: cladding index.
        layer_trench: for the trench.
        p_start: first tooth.
        n_periods: number of grating teeth.
        end_straight_length: at the end of straight.
        taper: taper function.
        cross_section: cross_section spec.

                      fiber

                   /  /  /  /
                  /  /  /  /
                _|-|_|-|_|-|___
        WG  o1  ______________|
    """
    return _components.grating_coupler_te(
        polarization=polarization,
        taper_length=taper_length,
        taper_angle=taper_angle,
        trenches_extra_angle=trenches_extra_angle,
        wavelength=wavelength,
        fiber_angle=fiber_angle,
        grating_line_width=grating_line_width,
        neff=neff,
        ncladding=ncladding,
        layer_trench=layer_trench,
        p_start=p_start,
        n_periods=n_periods,
        end_straight_length=end_straight_length,
        taper=taper,
        cross_section=cross_section,
    )


@gf.cell(tags=["grating_couplers"], schematic_function=grating_coupler_schematic)
def grating_coupler_tm(
    polarization: str = "tm",
    taper_length: float = 16.6,
    taper_angle: float = 30.0,
    trenches_extra_angle: float = 9.0,
    wavelength: float = 1.53,
    fiber_angle: float = 15.0,
    grating_line_width: float = 0.6,
    neff: float = 1.8,
    ncladding: float = 1.443,
    layer_trench: LayerSpec = "SHALLOW_ETCH",
    p_start: int = 26,
    n_periods: int = 30,
    end_straight_length: float = 0.2,
    taper: ComponentSpec = "taper",
    cross_section: CrossSectionSpec = "strip",
) -> gf.Component:
    r"""Returns Grating coupler with defined trenches.

    Some foundries define the grating coupler by a shallow etch step (trenches)
    Others define the slab that they keep (see grating_coupler_elliptical)

    Args:
        polarization: 'te' or 'tm'.
        taper_length: taper length from straight I/O.
        taper_angle: grating flare angle.
        trenches_extra_angle: extra angle for the trenches.
        wavelength: grating transmission central wavelength.
        fiber_angle: fibre polish angle in degrees.
        grating_line_width: of the 220 ridge.
        neff: tooth effective index.
        ncladding: cladding index.
        layer_trench: for the trench.
        p_start: first tooth.
        n_periods: number of grating teeth.
        end_straight_length: at the end of straight.
        taper: taper function.
        cross_section: cross_section spec.

                      fiber

                   /  /  /  /
                  /  /  /  /
                _|-|_|-|_|-|___
        WG  o1  ______________|
    """
    return _components.grating_coupler_tm(
        polarization=polarization,
        taper_length=taper_length,
        taper_angle=taper_angle,
        trenches_extra_angle=trenches_extra_angle,
        wavelength=wavelength,
        fiber_angle=fiber_angle,
        grating_line_width=grating_line_width,
        neff=neff,
        ncladding=ncladding,
        layer_trench=layer_trench,
        p_start=p_start,
        n_periods=n_periods,
        end_straight_length=end_straight_length,
        taper=taper,
        cross_section=cross_section,
    )


@gf.cell(tags=["grating_couplers"])
def grating_coupler_tree(
    n: int = 4,
    straight_spacing: float = 4.0,
    grating_coupler: ComponentSpec = "grating_coupler_elliptical_te",
    with_loopback: bool = False,
    bend: ComponentSpec = "bend_euler",
    fanout_length: float = 0.0,
    cross_section: CrossSectionSpec = "strip",
    **kwargs: Any,
) -> gf.Component:
    r"""Array of straights connected with grating couplers.

    useful to align the 4 corners of the chip

    Args:
        n: number of gratings.
        straight_spacing: in um.
        grating_coupler: spec.
        with_loopback: adds loopback.
        bend: bend spec.
        fanout_length: in um.
        cross_section: cross_section function.
        kwargs: additional arguments.
    """
    return _components.grating_coupler_tree(
        n=n,
        straight_spacing=straight_spacing,
        grating_coupler=grating_coupler,
        with_loopback=with_loopback,
        bend=bend,
        fanout_length=fanout_length,
        cross_section=cross_section,
        **kwargs,
    )


__all__ = [
    "grating_coupler_array",
    "grating_coupler_dual_pol",
    "grating_coupler_elliptical",
    "grating_coupler_elliptical_arbitrary",
    "grating_coupler_elliptical_lumerical",
    "grating_coupler_elliptical_lumerical_etch70",
    "grating_coupler_elliptical_te",
    "grating_coupler_elliptical_tm",
    "grating_coupler_elliptical_trenches",
    "grating_coupler_elliptical_uniform",
    "grating_coupler_loss",
    "grating_coupler_rectangular",
    "grating_coupler_rectangular_arbitrary",
    "grating_coupler_te",
    "grating_coupler_tm",
    "grating_coupler_tree",
]
