"""Generated tapers cells.

Generated by .github/generate_cells.py. Do not edit by hand.
Run ``make cells-regen`` to regenerate, ``make cells-check`` to verify.
"""

from __future__ import annotations

import gdsfactory as gf
from gdsfactory import components as _components
from gdsfactory.components.tapers.taper_adiabatic import (
    neff_TE1550SOI_220nm as _default_neff_TE1550SOI_220nm,
)
from gdsfactory.components.tapers.taper_from_csv import (
    data as _default_data,
)
from gdsfactory.typings import *  # noqa: F403

from gpdk.cells._schematic import (
    taper_schematic,
    transition_schematic,
)


@gf.cell(tags=["tapers"], schematic_function=taper_schematic)
def ramp(
    length: float = 10.0,
    width1: float = 5.0,
    width2: float | None = 8.0,
    layer: LayerSpec = "WG",
) -> gf.Component:
    r"""Return a ramp component.

    Based on phidl.

    Args:
        length: Length of the ramp section.
        width1: Width of the start of the ramp section.
        width2: Width of the end of the ramp section (defaults to width1).
        layer: Specific layer to put polygon geometry on.
    """
    return _components.ramp(
        length=length,
        width1=width1,
        width2=width2,
        layer=layer,
    )


@gf.cell(tags=["tapers"], schematic_function=taper_schematic)
def taper(
    length: float = 10.0,
    width1: float = 0.5,
    width2: float | None = None,
    layer: LayerSpec | None = None,
    port: Port | None = None,
    with_two_ports: bool = True,
    cross_section: CrossSectionSpec = "strip",
    port_names: tuple[str, str] = ("o1", "o2"),
    port_types: tuple[str, str] = ("optical", "optical"),
    with_bbox: bool = True,
) -> gf.Component:
    r"""Linear taper, which tapers only the main cross section section.

    Args:
        length: taper length.
        width1: width of the west/left port.
        width2: width of the east/right port. Defaults to width1.
        layer: layer for the taper.
        port: can taper from a port instead of defining width1.
        with_two_ports: includes a second port.
            False for terminator and edge coupler fiber interface.
        cross_section: specification (CrossSection, string, CrossSectionFactory dict).
        port_names: input and output port names. Second name only used if with_two_ports.
        port_types: input and output port types. Second type only used if with_two_ports.
        with_bbox: box in bbox_layers and bbox_offsets to avoid DRC sharp edges.
    """
    return _components.taper(
        length=length,
        width1=width1,
        width2=width2,
        layer=layer,
        port=port,
        with_two_ports=with_two_ports,
        cross_section=cross_section,
        port_names=port_names,
        port_types=port_types,
        with_bbox=with_bbox,
    )


@gf.cell(tags=["tapers"], schematic_function=taper_schematic)
def taper_0p5_to_3_l36(
    filepath: Path = _default_data / "taper_strip_0p5_3_36.csv",
    cross_section: CrossSectionSpec = "strip",
) -> gf.Component:
    r"""Returns taper from CSV file.

    Args:
        filepath: for CSV file.
        cross_section: specification (CrossSection, string, CrossSectionFactory dict).
    """
    return _components.taper_0p5_to_3_l36(
        filepath=filepath,
        cross_section=cross_section,
    )


@gf.cell(tags=["tapers"], schematic_function=taper_schematic)
def taper_adiabatic(
    width1: float = 0.5,
    width2: float = 5.0,
    length: float = 0,
    neff_w: Callable[[float], float] = _default_neff_TE1550SOI_220nm,
    alpha: float = 1,
    wavelength: float = 1.55,
    npoints: int = 200,
    cross_section: CrossSectionSpec = "strip",
    max_length: float = 200,
) -> gf.Component:
    r"""Returns a straight adiabatic_taper from an effective index callable.

    Args:
        width1: initial width.
        width2: final width.
        length: 0 uses the optimized length, and otherwise the optimal shape is compressed/stretched to the specified length.
        neff_w: a callable that returns the effective index as a function of width
                - By default, will use a compact model of neff(y) for fundamental 1550 nm TE mode of 220nm-thick core with 3.45 index, fully clad with 1.44 index. Many coefficients are needed to capture the behaviour.
        alpha: parameter that scales the rate of width change.
                - closer to 0 means longer and more adiabatic;
                - 1 is the intuitive limit beyond which higher order modes are excited;
                - [2] reports good performance up to 1.4 for fundamental TE in SOI (for multiple core thicknesses)
        wavelength: wavelength in um.
        npoints: number of points for sampling.
        cross_section: cross_section specification.
        max_length: maximum length for the taper.

    References:
        [1] Burns, W. K., et al. "Optical waveguide parabolic coupling horns." Appl. Phys. Lett., vol. 30, no. 1, 1 Jan. 1977, pp. 28-30, doi:10.1063/1.89199.
        [2] Fu, Yunfei, et al. "Efficient adiabatic silicon-on-insulator waveguide taper." Photonics Res., vol. 2, no. 3, 1 June 2014, pp. A41-A44, doi:10.1364/PRJ.2.000A41.
        npoints: number of points for sampling
    """
    return _components.taper_adiabatic(
        width1=width1,
        width2=width2,
        length=length,
        neff_w=neff_w,
        alpha=alpha,
        wavelength=wavelength,
        npoints=npoints,
        cross_section=cross_section,
        max_length=max_length,
    )


@gf.cell(tags=["tapers"], schematic_function=transition_schematic)
def taper_cross_section(
    cross_section1: CrossSectionSpec = "strip_rib_tip",
    cross_section2: CrossSectionSpec = "rib2",
    length: float = 10,
    npoints: int = 100,
    linear: bool = False,
    width_type: str = "sine",
    exclude_layers: LayerSpecs | None = None,
) -> gf.Component:
    r"""Returns taper transition between cross_section1 and cross_section2.

    Args:
        cross_section1: start cross_section factory.
        cross_section2: end cross_section factory.
        length: transition length.
        npoints: number of points.
        linear: shape of the transition, sine when False.
        width_type: shape of the transition ONLY IF linear is False
        exclude_layers: layers to exclude from the transition.
            Sections on these layers will be omitted from the component.

    ```text
                           _____________________
                          /
                  _______/______________________
                        /
       cross_section1  |        cross_section2
                  ______\_______________________
                         \
                          \_____________________
    ```
    """
    return _components.taper_cross_section(
        cross_section1=cross_section1,
        cross_section2=cross_section2,
        length=length,
        npoints=npoints,
        linear=linear,
        width_type=width_type,
        exclude_layers=exclude_layers,
    )


@gf.cell(tags=["tapers"], schematic_function=transition_schematic)
def taper_cross_section_linear(
    cross_section1: CrossSectionSpec = "strip_rib_tip",
    cross_section2: CrossSectionSpec = "rib2",
    length: float = 10,
    npoints: int = 2,
    linear: bool = True,
    width_type: str = "sine",
    exclude_layers: LayerSpecs | None = None,
) -> gf.Component:
    r"""Returns taper transition between cross_section1 and cross_section2.

    Args:
        cross_section1: start cross_section factory.
        cross_section2: end cross_section factory.
        length: transition length.
        npoints: number of points.
        linear: shape of the transition, sine when False.
        width_type: shape of the transition ONLY IF linear is False
        exclude_layers: layers to exclude from the transition.
            Sections on these layers will be omitted from the component.

    ```text
                           _____________________
                          /
                  _______/______________________
                        /
       cross_section1  |        cross_section2
                  ______\_______________________
                         \
                          \_____________________
    ```
    """
    return _components.taper_cross_section_linear(
        cross_section1=cross_section1,
        cross_section2=cross_section2,
        length=length,
        npoints=npoints,
        linear=linear,
        width_type=width_type,
        exclude_layers=exclude_layers,
    )


@gf.cell(tags=["tapers"], schematic_function=transition_schematic)
def taper_cross_section_parabolic(
    cross_section1: CrossSectionSpec = "strip_rib_tip",
    cross_section2: CrossSectionSpec = "rib2",
    length: float = 10,
    npoints: int = 101,
    linear: bool = False,
    width_type: str = "parabolic",
    exclude_layers: LayerSpecs | None = None,
) -> gf.Component:
    r"""Returns taper transition between cross_section1 and cross_section2.

    Args:
        cross_section1: start cross_section factory.
        cross_section2: end cross_section factory.
        length: transition length.
        npoints: number of points.
        linear: shape of the transition, sine when False.
        width_type: shape of the transition ONLY IF linear is False
        exclude_layers: layers to exclude from the transition.
            Sections on these layers will be omitted from the component.

    ```text
                           _____________________
                          /
                  _______/______________________
                        /
       cross_section1  |        cross_section2
                  ______\_______________________
                         \
                          \_____________________
    ```
    """
    return _components.taper_cross_section_parabolic(
        cross_section1=cross_section1,
        cross_section2=cross_section2,
        length=length,
        npoints=npoints,
        linear=linear,
        width_type=width_type,
        exclude_layers=exclude_layers,
    )


@gf.cell(tags=["tapers"], schematic_function=transition_schematic)
def taper_cross_section_sine(
    cross_section1: CrossSectionSpec = "strip_rib_tip",
    cross_section2: CrossSectionSpec = "rib2",
    length: float = 10,
    npoints: int = 101,
    linear: bool = False,
    width_type: str = "sine",
    exclude_layers: LayerSpecs | None = None,
) -> gf.Component:
    r"""Returns taper transition between cross_section1 and cross_section2.

    Args:
        cross_section1: start cross_section factory.
        cross_section2: end cross_section factory.
        length: transition length.
        npoints: number of points.
        linear: shape of the transition, sine when False.
        width_type: shape of the transition ONLY IF linear is False
        exclude_layers: layers to exclude from the transition.
            Sections on these layers will be omitted from the component.

    ```text
                           _____________________
                          /
                  _______/______________________
                        /
       cross_section1  |        cross_section2
                  ______\_______________________
                         \
                          \_____________________
    ```
    """
    return _components.taper_cross_section_sine(
        cross_section1=cross_section1,
        cross_section2=cross_section2,
        length=length,
        npoints=npoints,
        linear=linear,
        width_type=width_type,
        exclude_layers=exclude_layers,
    )


@gf.cell(tags=["tapers"], schematic_function=taper_schematic)
def taper_electrical(
    length: float = 10.0,
    width1: float = 0.5,
    width2: float | None = None,
    layer: LayerSpec | None = None,
    port: Port | None = None,
    with_two_ports: bool = True,
    cross_section: CrossSectionSpec = "metal_routing",
    port_names: tuple[str, str] = ("e1", "e2"),
    port_types: tuple[str, str] = ("electrical", "electrical"),
    with_bbox: bool = True,
) -> gf.Component:
    r"""Linear taper, which tapers only the main cross section section.

    Args:
        length: taper length.
        width1: width of the west/left port.
        width2: width of the east/right port. Defaults to width1.
        layer: layer for the taper.
        port: can taper from a port instead of defining width1.
        with_two_ports: includes a second port.
            False for terminator and edge coupler fiber interface.
        cross_section: specification (CrossSection, string, CrossSectionFactory dict).
        port_names: input and output port names. Second name only used if with_two_ports.
        port_types: input and output port types. Second type only used if with_two_ports.
        with_bbox: box in bbox_layers and bbox_offsets to avoid DRC sharp edges.
    """
    return _components.taper_electrical(
        length=length,
        width1=width1,
        width2=width2,
        layer=layer,
        port=port,
        with_two_ports=with_two_ports,
        cross_section=cross_section,
        port_names=port_names,
        port_types=port_types,
        with_bbox=with_bbox,
    )


@gf.cell(tags=["tapers"], schematic_function=taper_schematic)
def taper_from_csv(
    filepath: Path = _default_data / "taper_strip_0p5_3_36.csv",
    cross_section: CrossSectionSpec = "strip",
) -> gf.Component:
    r"""Returns taper from CSV file.

    Args:
        filepath: for CSV file.
        cross_section: specification (CrossSection, string, CrossSectionFactory dict).
    """
    return _components.taper_from_csv(
        filepath=filepath,
        cross_section=cross_section,
    )


@gf.cell(tags=["tapers"], schematic_function=taper_schematic)
def taper_hecken(
    length: float = 200,
    B: float = 4.0091,
    dielectric_thickness: float = 0.25,
    eps_r: float = 2,
    Lk_per_sq: float = 2.5e-10,
    Z1: float | None = 50,
    Z2: float | None = 100,
    width1: float | None = None,
    width2: float | None = None,
    num_pts: int = 100,
    layer: LayerSpec = "WG",
) -> gf.Component:
    r"""Creates a Hecken-tapered microstrip.

    Args:
        length: Length of the microstrip.
        B: Controls the intensity of the taper.
        dielectric_thickness: Thickness of the substrate.
        eps_r: Dielectric constant of the substrate.
        Lk_per_sq: Kinetic inductance per square of the microstrip.
        Z1: Impedance of the left side region of the microstrip.
        Z2: Impedance of the right side region of the microstrip.
        width1: Width of the left side of the microstrip.
        width2: Width of the right side of the microstrip.
        num_pts: Number of points comprising the curve of the entire microstrip.
        layer: Specific layer(s) to put polygon geometry on.

    Returns:
        Component containing a Hecken-tapered microstrip.
    """
    return _components.taper_hecken(
        length=length,
        B=B,
        dielectric_thickness=dielectric_thickness,
        eps_r=eps_r,
        Lk_per_sq=Lk_per_sq,
        Z1=Z1,
        Z2=Z2,
        width1=width1,
        width2=width2,
        num_pts=num_pts,
        layer=layer,
    )


@gf.cell(tags=["tapers"], schematic_function=taper_schematic)
def taper_meander(
    x_taper: tuple[float, ...] | None = None,
    w_taper: tuple[float, ...] | None = None,
    meander_length: float = 1000,
    spacing_factor: float = 3,
    min_spacing: float = 0.5,
    layer: LayerSpec = "WG",
) -> gf.Component:
    r"""Create a meander from arrays of x-positions and widths.

    Typically used for creating meandered tapers.

    Args:
        x_taper: The x-coordinates of the data points, must be increasing.
        w_taper: The widths at each x-coordinate, same length as x_taper.
        meander_length: Length of each section of the meander.
        spacing_factor: Multiplicative spacing factor between adjacent meanders.
        min_spacing: Minimum spacing between adjacent meanders.
        layer: Specific layer(s) to put polygon geometry on.

    Returns:
        Component containing the meandered taper.
    """
    return _components.taper_meander(
        x_taper=x_taper,
        w_taper=w_taper,
        meander_length=meander_length,
        spacing_factor=spacing_factor,
        min_spacing=min_spacing,
        layer=layer,
    )


@gf.cell(tags=["tapers"], schematic_function=transition_schematic)
def taper_nc_sc(
    width1: float = 1,
    width2: float = 0.5,
    length: float = 20,
    layer_wg: LayerSpec = "WG",
    layer_nitride: LayerSpec = "WGN",
    width_tip_nitride: float = 0.15,
    width_tip_silicon: float = 0.15,
    cross_section: CrossSectionSpec = "strip",
) -> gf.Component:
    r"""Taper from nitride to strip.

    Args:
        width1: nitride width.
        width2: silicon width.
        length: taper length.
        layer_wg: nitride layer.
        layer_nitride: strip layer.
        width_tip_nitride: tip width for nitride.
        width_tip_silicon: tip width for strip.
        cross_section: cross_section specification.
    """
    return _components.taper_nc_sc(
        width1=width1,
        width2=width2,
        length=length,
        layer_wg=layer_wg,
        layer_nitride=layer_nitride,
        width_tip_nitride=width_tip_nitride,
        width_tip_silicon=width_tip_silicon,
        cross_section=cross_section,
    )


@gf.cell(tags=["tapers"], schematic_function=taper_schematic)
def taper_parabolic(
    length: float = 20,
    width1: float = 0.5,
    width2: float = 5.0,
    exp: float = 0.5,
    npoints: int = 100,
    layer: LayerSpec = "WG",
) -> gf.Component:
    r"""Returns a parabolic_taper.

    Args:
        length: in um.
        width1: in um.
        width2: in um.
        exp: exponent.
        npoints: number of points.
        layer: layer spec.
    """
    return _components.taper_parabolic(
        length=length,
        width1=width1,
        width2=width2,
        exp=exp,
        npoints=npoints,
        layer=layer,
    )


@gf.cell(tags=["tapers"], schematic_function=transition_schematic)
def taper_sc_nc(
    width1: float = 0.5,
    width2: float = 1,
    length: float = 20,
    layer_wg: LayerSpec = "WG",
    layer_nitride: LayerSpec = "WGN",
    width_tip_nitride: float = 0.15,
    width_tip_silicon: float = 0.15,
    cross_section: CrossSectionSpec = "strip",
) -> gf.Component:
    r"""Taper from strip to nitride.

    Args:
        width1: strip width.
        width2: nitride width.
        length: taper length.
        layer_wg: strip layer.
        layer_nitride: nitride layer.
        width_tip_nitride: tip width for nitride.
        width_tip_silicon: tip width for strip.
        cross_section: cross_section specification.
    """
    return _components.taper_sc_nc(
        width1=width1,
        width2=width2,
        length=length,
        layer_wg=layer_wg,
        layer_nitride=layer_nitride,
        width_tip_nitride=width_tip_nitride,
        width_tip_silicon=width_tip_silicon,
        cross_section=cross_section,
    )


@gf.cell(tags=["tapers"], schematic_function=transition_schematic)
def taper_strip_to_ridge(
    length: float = 10.0,
    width1: float = 0.5,
    width2: float = 0.5,
    w_slab1: float = 0.15,
    w_slab2: float = 6.0,
    layer_wg: LayerSpec = "WG",
    layer_slab: LayerSpec = "SLAB90",
    cross_section: CrossSectionSpec = "strip",
    use_slab_port: bool = False,
    slab_port_layer: LayerSpec | None = None,
) -> gf.Component:
    r"""Linear taper from strip to rib.

    Args:
        length: taper length (um).
        width1: in um.
        width2: in um.
        w_slab1: slab width in um.
        w_slab2: slab width in um.
        layer_wg: for input waveguide.
        layer_slab: for output waveguide with slab.
        cross_section: for input waveguide.
        use_slab_port: if True adds a second port for the slab.
        slab_port_layer: if specified, overrides the layer for the slab port.

    ```text
                      __________________________
                     /           |
             _______/____________|______________
                   /             |
       width1     |w_slab1       | w_slab2  width2
             ______\_____________|______________
                    \            |
                     \__________________________
    ```
    """
    return _components.taper_strip_to_ridge(
        length=length,
        width1=width1,
        width2=width2,
        w_slab1=w_slab1,
        w_slab2=w_slab2,
        layer_wg=layer_wg,
        layer_slab=layer_slab,
        cross_section=cross_section,
        use_slab_port=use_slab_port,
        slab_port_layer=slab_port_layer,
    )


@gf.cell(tags=["tapers"], schematic_function=transition_schematic)
def taper_strip_to_ridge_trenches(
    length: float = 10.0,
    width: float = 0.5,
    slab_offset: float = 3.0,
    trench_width: float = 2.0,
    trench_layer: LayerSpec = "DEEP_ETCH",
    layer_wg: LayerSpec = "WG",
    trench_offset: float = 0.1,
) -> gf.Component:
    r"""Defines taper using trenches to define the etch.

    Args:
        length: in um.
        width: in um.
        slab_offset: in um.
        trench_width: in um.
        trench_layer: trench layer.
        layer_wg: waveguide layer.
        trench_offset: after waveguide in um.
    """
    return _components.taper_strip_to_ridge_trenches(
        length=length,
        width=width,
        slab_offset=slab_offset,
        trench_width=trench_width,
        trench_layer=trench_layer,
        layer_wg=layer_wg,
        trench_offset=trench_offset,
    )


@gf.cell(tags=["tapers"], schematic_function=transition_schematic)
def taper_strip_to_slab150(
    length: float = 10.0,
    width1: float = 0.5,
    width2: float = 0.5,
    w_slab1: float = 0.15,
    w_slab2: float = 6.0,
    layer_wg: LayerSpec = "WG",
    layer_slab: LayerSpec = "SLAB150",
    cross_section: CrossSectionSpec = "strip",
    use_slab_port: bool = False,
    slab_port_layer: LayerSpec | None = None,
) -> gf.Component:
    r"""Linear taper from strip to rib.

    Args:
        length: taper length (um).
        width1: in um.
        width2: in um.
        w_slab1: slab width in um.
        w_slab2: slab width in um.
        layer_wg: for input waveguide.
        layer_slab: for output waveguide with slab.
        cross_section: for input waveguide.
        use_slab_port: if True adds a second port for the slab.
        slab_port_layer: if specified, overrides the layer for the slab port.

    ```text
                      __________________________
                     /           |
             _______/____________|______________
                   /             |
       width1     |w_slab1       | w_slab2  width2
             ______\_____________|______________
                    \            |
                     \__________________________
    ```
    """
    return _components.taper_strip_to_slab150(
        length=length,
        width1=width1,
        width2=width2,
        w_slab1=w_slab1,
        w_slab2=w_slab2,
        layer_wg=layer_wg,
        layer_slab=layer_slab,
        cross_section=cross_section,
        use_slab_port=use_slab_port,
        slab_port_layer=slab_port_layer,
    )


@gf.cell(tags=["tapers"], schematic_function=taper_schematic)
def taper_w10_l100(
    filepath: Path = _default_data / "taper_strip_0p5_10_100.csv",
    cross_section: CrossSectionSpec = "strip",
) -> gf.Component:
    r"""Returns taper from CSV file.

    Args:
        filepath: for CSV file.
        cross_section: specification (CrossSection, string, CrossSectionFactory dict).
    """
    return _components.taper_w10_l100(
        filepath=filepath,
        cross_section=cross_section,
    )


@gf.cell(tags=["tapers"], schematic_function=taper_schematic)
def taper_w10_l150(
    filepath: Path = _default_data / "taper_strip_0p5_10_150.csv",
    cross_section: CrossSectionSpec = "strip",
) -> gf.Component:
    r"""Returns taper from CSV file.

    Args:
        filepath: for CSV file.
        cross_section: specification (CrossSection, string, CrossSectionFactory dict).
    """
    return _components.taper_w10_l150(
        filepath=filepath,
        cross_section=cross_section,
    )


@gf.cell(tags=["tapers"], schematic_function=taper_schematic)
def taper_w10_l200(
    filepath: Path = _default_data / "taper_strip_0p5_10_200.csv",
    cross_section: CrossSectionSpec = "strip",
) -> gf.Component:
    r"""Returns taper from CSV file.

    Args:
        filepath: for CSV file.
        cross_section: specification (CrossSection, string, CrossSectionFactory dict).
    """
    return _components.taper_w10_l200(
        filepath=filepath,
        cross_section=cross_section,
    )


@gf.cell(tags=["tapers"], schematic_function=taper_schematic)
def taper_w11_l200(
    filepath: Path = _default_data / "taper_strip_0p5_11_200.csv",
    cross_section: CrossSectionSpec = "strip",
) -> gf.Component:
    r"""Returns taper from CSV file.

    Args:
        filepath: for CSV file.
        cross_section: specification (CrossSection, string, CrossSectionFactory dict).
    """
    return _components.taper_w11_l200(
        filepath=filepath,
        cross_section=cross_section,
    )


@gf.cell(tags=["tapers"], schematic_function=taper_schematic)
def taper_w12_l200(
    filepath: Path = _default_data / "taper_strip_0p5_12_200.csv",
    cross_section: CrossSectionSpec = "strip",
) -> gf.Component:
    r"""Returns taper from CSV file.

    Args:
        filepath: for CSV file.
        cross_section: specification (CrossSection, string, CrossSectionFactory dict).
    """
    return _components.taper_w12_l200(
        filepath=filepath,
        cross_section=cross_section,
    )


__all__ = [
    "ramp",
    "taper",
    "taper_0p5_to_3_l36",
    "taper_adiabatic",
    "taper_cross_section",
    "taper_cross_section_linear",
    "taper_cross_section_parabolic",
    "taper_cross_section_sine",
    "taper_electrical",
    "taper_from_csv",
    "taper_hecken",
    "taper_meander",
    "taper_nc_sc",
    "taper_parabolic",
    "taper_sc_nc",
    "taper_strip_to_ridge",
    "taper_strip_to_ridge_trenches",
    "taper_strip_to_slab150",
    "taper_w10_l100",
    "taper_w10_l150",
    "taper_w10_l200",
    "taper_w11_l200",
    "taper_w12_l200",
]
