"""Generated texts cells.

Generated by .github/generate_cells.py. Do not edit by hand.
Run ``make cells-regen`` to regenerate, ``make cells-check`` to verify.
"""

from __future__ import annotations

import gdsfactory as gf
from gdsfactory import components as _components
from gdsfactory.components.texts.text_freetype import (
    PATH as _default_PATH,
)
from gdsfactory.components.texts.text_rectangular import (
    rectangular_font as _default_rectangular_font,
)
from gdsfactory.components.texts.text_rectangular import (
    text_rectangular as _default_text_rectangular,
)
from gdsfactory.typings import *  # noqa: F403


@gf.cell(tags=["texts"])
def pixel_array(
    pixels: str = "\n XXX\nX   X\nXXXXX\nX   X\nX   X\n\n",
    pixel_size: float = 10.0,
    layer: LayerSpec = "M1",
) -> gf.Component:
    r"""Returns a pixel component from a string representing the pixels.

    Args:
        pixels: string representing the pixels
        pixel_size: width/height for each pixel
        layer: layer for each pixel
    """
    return _components.pixel_array(
        pixels=pixels,
        pixel_size=pixel_size,
        layer=layer,
    )


@gf.cell(tags=["texts"])
def text(
    text: str = "abcd",
    size: float = 10.0,
    position: Coordinate = (0, 0),
    justify: str = "left",
    layer: LayerSpec = "WG",
) -> gf.Component:
    r"""Text shapes.

    Args:
        text: string.
        size: in um of each character.
        position: x, y position.
        justify: left, right, center.
        layer: for the text.
    """
    return _components.text(
        text=text,
        size=size,
        position=position,
        justify=justify,
        layer=layer,
    )


@gf.cell(tags=["texts"])
def text_freetype(
    text: str = "a",
    size: int = 10,
    justify: str = "left",
    font: PathType = _default_PATH.font_ocr,
    layer: LayerSpec = "WG",
    layers: LayerSpecs | None = None,
) -> gf.Component:
    r"""Returns text Component.

    Args:
        text: string.
        size: in um.
        justify: left, right, center.
        font: Font face to use. Default DEPLOF does not require additional libraries,
            otherwise freetype load fonts. You can choose font by name
            (e.g. "Times New Roman"), or by file OTF or TTF filepath.
        layer: list of layers to use for the text.
        layers: list of layers to use for the text.
    """
    return _components.text_freetype(
        text=text,
        size=size,
        justify=justify,
        font=font,
        layer=layer,
        layers=layers,
    )


@gf.cell(tags=["texts"])
def text_klayout(
    text: str = "a",
    layer: LayerSpec = "WG",
    layers: LayerSpecs | None = None,
    bbox_layers: LayerSpecs | None = None,
) -> gf.Component:
    r"""Returns a text component.

    Args:
        text: string.
        layer: text layer.
        layers: layers for the text.
        bbox_layers: layers for the text bounding box.
    """
    return _components.text_klayout(
        text=text,
        layer=layer,
        layers=layers,
        bbox_layers=bbox_layers,
    )


@gf.cell(tags=["texts"])
def text_lines(
    text: tuple[str, ...] = ("Chip", "01"),
    size: float = 0.4,
    layer: LayerSpec = "WG",
) -> gf.Component:
    r"""Returns a Component from a text lines.

    Args:
        text: list of strings.
        size: text size.
        layer: text layer.
    """
    return _components.text_lines(
        text=text,
        size=size,
        layer=layer,
    )


@gf.cell(tags=["texts"])
def text_rectangular(
    text: str = "abcd",
    size: float = 10.0,
    position: tuple[float, float] = (0.0, 0.0),
    justify: str = "left",
    layer: LayerSpec | None = "WG",
    layers: LayerSpecs | None = None,
    font: Callable[..., dict[str, str]] = _default_rectangular_font,
) -> gf.Component:
    r"""Pixel based font, guaranteed to be manhattan, without acute angles.

    Args:
        text: string.
        size: pixel size in um.
        position: coordinate.
        justify: left, right or center.
        layer: for text.
        layers: optional for duplicating the text.
        font: function that returns dictionary of characters.
    """
    return _components.text_rectangular(
        text=text,
        size=size,
        position=position,
        justify=justify,
        layer=layer,
        layers=layers,
        font=font,
    )


@gf.cell(tags=["texts"])
def text_rectangular_multi_layer(
    text: str = "abcd",
    layers: LayerSpecs = ("WG", "M1", "M2", "MTOP"),
    text_factory: ComponentSpec = _default_text_rectangular,
    **kwargs: Any,
) -> gf.Component:
    r"""Returns rectangular text in different layers.

    Args:
        text: string of text.
        layers: list of layers to replicate the text.
        text_factory: function to create the text Components.
        kwargs: keyword arguments for text_factory.

    Keyword Args:
        size: pixel size.
        position: coordinate.
        justify: left, right or center.
        font: function that returns dictionary of characters.
    """
    return _components.text_rectangular_multi_layer(
        text=text,
        layers=layers,
        text_factory=text_factory,
        **kwargs,
    )


__all__ = [
    "pixel_array",
    "text",
    "text_freetype",
    "text_klayout",
    "text_lines",
    "text_rectangular",
    "text_rectangular_multi_layer",
]
