"""Generate gpdk/cells/ from the pinned gdsfactory generic PDK.

This script is the only writer of ``gpdk/cells/``. Run it with ``--check`` to verify the
committed library still matches the pinned gdsfactory, or ``--write`` to regenerate.

There is no manual override. A cell that cannot be expressed as a pure re-emission of a
gdsfactory function must be fixed in gdsfactory core and pulled in via a pin bump.
"""

from __future__ import annotations

import argparse
import ast
import difflib
import functools
import inspect
import pathlib
import re
import subprocess
import sys
import tempfile
from collections import defaultdict
from dataclasses import dataclass, field

import gdsfactory as gf
from gdsfactory.get_factories import get_cells

REPO = pathlib.Path(__file__).resolve().parent.parent
CELLS_DIR = REPO / "gpdk" / "cells"
FUNCTIONS_CATEGORY = "functions"
SCHEMATIC_MODULE = "gdsfactory.components._schematic"

HEADER = '''"""{summary}

Generated by .github/generate_cells.py. Do not edit by hand.
Run ``make cells-regen`` to regenerate, ``make cells-check`` to verify.
"""

from __future__ import annotations

import gdsfactory as gf
from gdsfactory.typings import *  # noqa: F403
'''


@dataclass
class CellSpec:
    """Everything needed to render one wrapper."""

    name: str
    category: str
    registry_module: str
    source_module: str
    source_name: str
    signature: inspect.Signature
    docstring: str
    tags: tuple[str, ...] = ()
    schematic_function: str | None = None
    source_defaults: dict[str, str] = field(default_factory=dict)


def _unwrap(obj):
    """Follow partial and decorator chains down to the defining function."""
    while isinstance(obj, functools.partial):
        obj = obj.func
    return inspect.unwrap(obj)


def _category(base) -> str:
    module = base.__module__
    if module.startswith("gdsfactory.components."):
        return module.split(".")[2]
    return FUNCTIONS_CATEGORY


@functools.cache
def _module_ast(path: str) -> ast.Module:
    return ast.parse(pathlib.Path(path).read_text())


def _decorator_kwargs(base) -> dict[str, str]:
    """Read the gf.cell decorator's keyword arguments from gdsfactory's source."""
    try:
        path = inspect.getsourcefile(base)
    except TypeError:
        return {}
    if path is None:
        return {}
    tree = _module_ast(path)
    source = pathlib.Path(path).read_text()
    for node in ast.walk(tree):
        if not isinstance(node, ast.FunctionDef) or node.name != base.__name__:
            continue
        for dec in node.decorator_list:
            if not isinstance(dec, ast.Call):
                continue
            return {
                kw.arg: ast.get_source_segment(source, kw.value)
                for kw in dec.keywords
                if kw.arg is not None
            }
    return {}


def _tags_for(name: str, base) -> tuple[str, ...]:
    """Read tags from the kfactory registry, falling back to the decorator source."""
    for key, factory in gf.kcl.factories.items():
        if key == name or key.startswith(f"{name}_gdsfactoryp"):
            tags = getattr(factory, "tags", None)
            if tags:
                return tuple(sorted(tags))
    raw = _decorator_kwargs(base).get("tags")
    if raw:
        return tuple(sorted(ast.literal_eval(raw)))
    return ()


def collect_cells() -> dict[str, CellSpec]:
    """Collect a CellSpec for every cell the generic PDK registers."""
    gf.gpdk.PDK.activate()
    # Record which module each name is importable from. Only 343 of the 359 live on
    # gdsfactory.components; the other 16 (rotate90, extract, add_fiber_array, ...) are
    # reachable ONLY via gdsfactory.containers, so a blanket `gf.c.<name>` call fails
    # for all of them. Verified: hasattr(gf.c, "rotate90") is False.
    from_components = get_cells([gf.components])
    from_containers = get_cells([gf.containers])
    registry: dict[str, object] = {}
    origin: dict[str, str] = {}
    for name, obj in from_components.items():
        registry[name] = obj
        origin[name] = "gdsfactory.components"
    for name, obj in from_containers.items():
        if name not in registry:
            registry[name] = obj
            origin[name] = "gdsfactory.containers"

    specs: dict[str, CellSpec] = {}
    for name in sorted(registry):
        obj = registry[name]
        base = _unwrap(obj)
        kwargs = _decorator_kwargs(base)
        schematic = kwargs.get("schematic_function")
        # inspect.getdoc(obj) on a functools.partial returns functools.partial's own
        # boilerplate class docstring (truthy), which would mask the real docstring
        # inherited from `base` — go straight to `base` for partials instead.
        if isinstance(obj, functools.partial):
            docstring = inspect.getdoc(base) or ""
        else:
            docstring = inspect.getdoc(obj) or inspect.getdoc(base) or ""
        signature = inspect.signature(obj)
        if _docstring_missing_params(docstring, signature):
            docstring = _synthesize_docstring(name, base, docstring, signature)
        specs[name] = CellSpec(
            name=name,
            category=_category(base),
            registry_module=origin[name],
            source_module=base.__module__,
            source_name=base.__name__,
            signature=signature,
            docstring=docstring,
            tags=_tags_for(name, base),
            schematic_function=schematic,
            source_defaults=_source_defaults(base),
        )
    return specs


_ARGS_HEADER_RE = re.compile(r"^\s*Args:\s*$")


def _docstring_missing_params(
    docstring: str, signature: inspect.Signature
) -> list[str]:
    r"""Signature parameter names not documented in the docstring's ``Args:`` section.

    This mirrors ``pydocstyle``'s D417 (Google convention) closely enough for our
    purposes, verified empirically against real gdsfactory docstrings:

    - A docstring with no ``Args:`` header at all: every parameter counts as missing.
    - A docstring with more than one ``Args:`` header (a real, if messy, gdsfactory
      pattern — e.g. ``ring_single_dut`` has two): pydocstyle does not merge or
      otherwise correctly parse duplicate headers. Verified with a minimal repro (two
      ``Args:`` sections, each documenting exactly one of two parameters): pydocstyle
      flags *both* parameters as missing, not just the ones actually undocumented. So
      every parameter counts as missing here too, rather than trying to reconcile
      which of the duplicate sections "wins". The header itself is matched
      line-by-line against ``^\\s*Args:\\s*$`` — not a bare substring count — so a
      legitimate, separate ``Keyword Args:`` section (also common in gdsfactory, for
      extra ``**kwargs``-forwarded parameters) is never miscounted as a second
      ``Args:`` header.
    - A docstring with exactly one ``Args:`` header: only the text up to the next blank
      line is the Args: section pydocstyle reads. A following ``Keyword Args:``
      section is real documentation but is not recognized by pydocstyle as covering
      ``Args:``.
    - Within that section, a parameter counts as documented if its name appears at the
      start of a line (after indentation), optionally preceded by ``**`` (for a
      rendered ``**kwargs:`` entry) and optionally followed by a parenthetical hint
      before the colon (e.g. ``parity (1 or -1):``) — both real upstream styles.
    - ``VAR_KEYWORD``/``VAR_POSITIONAL`` parameters (``**kwargs``) are never required to
      be individually documented: verified empirically (a minimal repro with an
      undocumented ``**kwargs`` parameter raises no D417), matching pydocstyle's
      standard treatment of pass-through parameters as exempt from this check.
    """
    param_names = [
        p
        for p, param in signature.parameters.items()
        if p != "self" and param.kind not in (param.VAR_KEYWORD, param.VAR_POSITIONAL)
    ]
    if not param_names:
        return []
    lines = docstring.splitlines()
    header_positions = [
        i for i, line in enumerate(lines) if _ARGS_HEADER_RE.match(line)
    ]
    if len(header_positions) != 1:
        return param_names
    section_lines: list[str] = []
    for line in lines[header_positions[0] + 1 :]:
        if line.strip() == "":
            break
        section_lines.append(line)
    section = "\n".join(section_lines)
    return [
        name
        for name in param_names
        if not re.search(
            rf"(?m)^\s*\*{{0,2}}{re.escape(name)}\s*(\([^)]*\))?\s*:", section
        )
    ]


def _synthesize_docstring(
    name: str, base, docstring: str, signature: inspect.Signature
) -> str:
    """Build a docstring with a complete ``Args:`` section for an under-documented cell.

    Used when the upstream docstring is missing an ``Args:`` section, or does not
    document every parameter (see ``_docstring_missing_params``).

    ``check-cells-structure`` (pdk-ci-workflow-public) only requires the *generated
    wrapper's own* docstring to contain a literal ``Args:`` line when the wrapper takes
    parameters — it does not check that section against gdsfactory's upstream docstring.
    So rather than refusing to generate a cell whose upstream docstring is missing or has
    an incomplete Args: section, synthesize one: keep any real prose *preceding* the
    first ``Args:`` header (if any) as the summary, and describe every parameter
    generically, pointing back at the real gdsfactory source. Anything from the first
    ``Args:`` onward in the original docstring (including a ``Keyword Args:`` or a
    second, duplicate ``Args:`` section) is dropped rather than kept as prose — keeping
    it would put the literal string ``Args:`` in the summary text, recreating the
    duplicate-header problem this function exists to avoid.
    """
    doc_lines = docstring.splitlines()
    header_positions = [
        i for i, line in enumerate(doc_lines) if _ARGS_HEADER_RE.match(line)
    ]
    prose_lines = doc_lines[: header_positions[0]] if header_positions else doc_lines
    summary = "\n".join(prose_lines).strip() or f"{name} cell."
    lines = [*summary.splitlines(), "", "Args:"]
    for param_name in signature.parameters:
        if param_name == "self":
            continue
        lines.append(
            f"    {param_name}: see :func:`{base.__module__}.{base.__name__}` for details."
        )
    return "\n".join(lines)


def _source_defaults(base) -> dict[str, str]:
    """Map parameter name to the source text of its default in gdsfactory."""
    try:
        path = inspect.getsourcefile(base)
    except TypeError:
        return {}
    if path is None:
        return {}
    source = pathlib.Path(path).read_text()
    tree = _module_ast(path)
    for node in ast.walk(tree):
        if not isinstance(node, ast.FunctionDef) or node.name != base.__name__:
            continue
        args = node.args
        positional = args.posonlyargs + args.args
        out: dict[str, str] = {}
        for arg, default in zip(
            positional[len(positional) - len(args.defaults) :], args.defaults
        ):
            out[arg.arg] = ast.get_source_segment(source, default)
        for arg, default in zip(args.kwonlyargs, args.kw_defaults):
            if default is not None:
                out[arg.arg] = ast.get_source_segment(source, default)
        return out
    return {}


def _render_annotation(annotation) -> str:
    """Render an annotation as source text.

    gdsfactory modules use ``from __future__ import annotations``, so annotations
    arrive as strings and must be emitted verbatim rather than repr'd.
    """
    if isinstance(annotation, str):
        return annotation
    return getattr(annotation, "__name__", None) or str(annotation)


def _is_literal(value) -> bool:
    try:
        return ast.literal_eval(repr(value)) == value
    except (ValueError, SyntaxError, TypeError):
        return False


def _free_names(expression: str) -> set[str]:
    """Root identifiers a default expression depends on."""
    try:
        tree = ast.parse(expression, mode="eval")
    except SyntaxError:
        return set()
    return {node.id for node in ast.walk(tree) if isinstance(node, ast.Name)}


def _alias_for(name: str) -> str:
    """A collision-proof local name for a non-literal default's upstream dependency.

    Every name a non-literal default expression depends on is imported under this
    alias, uniformly, never under its bare name. A bare import of the name is not
    collision-proof in two distinct ways, both observed in the full 355-cell registry:

    - The same name is independently re-exported by multiple sibling gdsfactory
      modules (e.g. ``select_ports_electrical`` from four different
      ``gdsfactory.routing.*`` modules — verified to be the identical object in every
      case, but still two `from x import name` / `from y import name` statements
      shadowing each other in the generated file).
    - The name collides with a cell of the same name generated later in the same
      category module (e.g. ``mzit`` is both a free name needed by ``mzit_lattice``'s
      default, and itself a registered cell rendered further down ``mzis.py``). Since
      all wrapper bodies are emitted after all imports, and cells are emitted in
      alphabetical order, the import would get silently shadowed by the `def mzit(...)`
      statement for any cell sorting after it — making the default resolve to gpdk's
      own wrapper instead of gdsfactory's plain function, purely by alphabetical
      accident. That is not a "pure re-emission" of that default.

    Aliasing is applied uniformly to every such import rather than only to the cells
    observed to collide today, since nothing about the pinned registry guarantees no
    new collision on a future pin bump.
    """
    return f"_default_{name}"


def _alias_free_names(expression: str, names: set[str]) -> str:
    """Rewrite root identifiers in a default expression to their aliased import names."""
    tree = ast.parse(expression, mode="eval")
    for node in ast.walk(tree):
        if isinstance(node, ast.Name) and node.id in names:
            node.id = _alias_for(node.id)
    return ast.unparse(tree)


def _render_default(spec: CellSpec, param: inspect.Parameter, source_defaults) -> str:
    """Render a default as source text, preferring a round-trippable repr."""
    if _is_literal(param.default):
        return repr(param.default)
    if param.name in source_defaults:
        return source_defaults[param.name]
    raise SystemExit(
        f"{spec.name}: default for {param.name!r} is neither a literal nor "
        f"recoverable from source ({param.default!r}). Fix this upstream in "
        f"{spec.source_module}."
    )


def _has_mutable_default(spec: CellSpec) -> bool:
    """Whether any parameter's literal default is a mutable container (dict/list/set)."""
    return any(
        param.default is not inspect.Parameter.empty
        and _is_literal(param.default)
        and isinstance(param.default, dict | list | set)
        for param in spec.signature.parameters.values()
    )


def _render_signature(
    spec: CellSpec, source_defaults: dict[str, str]
) -> tuple[str, set[str]]:
    """Render the parameter list, and the extra names its non-literal defaults need.

    ``VAR_KEYWORD`` (``**kwargs``) is re-emitted verbatim rather than rejected: gdsfactory
    uses it as a legitimate forwarding pattern (e.g. ``container()``-style wrappers), and
    kfactory's cell naming/caching hashes forwarded kwarg values correctly, so there is no
    collision risk from passing it through. ``VAR_POSITIONAL`` (``*args``) has never been
    observed on a registered cell; it stays a fail-loud tripwire rather than unused
    handling for a case that doesn't exist.

    A literal default that is a mutable container (dict/list/set) is re-emitted as-is:
    faithfully re-emitting gdsfactory's own default is the generator's job, not
    redesigning gdsfactory's API to avoid a mutable default (B006). ``render_module``
    adds a module-level ``# ruff: noqa: B006`` for any category that needs it, rather
    than an inline comment here — `ruff format` can rewrap a long literal across
    multiple lines, and would then relocate a trailing inline comment to the wrapped
    literal's closing line, away from the line the diagnostic actually anchors to.
    """
    parts: list[str] = []
    needed: set[str] = set()
    for param in spec.signature.parameters.values():
        if param.kind is param.VAR_POSITIONAL:
            raise SystemExit(
                f"{spec.name}: var-positional in signature {spec.signature}"
            )
        annotation = (
            f": {_render_annotation(param.annotation)}"
            if param.annotation is not inspect.Parameter.empty
            else ""
        )
        if param.kind is param.VAR_KEYWORD:
            parts.append(f"**{param.name}{annotation or ': Any'}")
            continue
        default = ""
        if param.default is not inspect.Parameter.empty:
            rendered = _render_default(spec, param, source_defaults)
            if not _is_literal(param.default):
                free = _free_names(rendered)
                needed |= free
                rendered = _alias_free_names(rendered, free)
            default = f" = {rendered}"
        parts.append(f"{param.name}{annotation}{default}")
    return ",\n    ".join(parts), needed


REGISTRY_ALIAS = {
    "gdsfactory.components": "_components",
    "gdsfactory.containers": "_containers",
}


def _render_call(spec: CellSpec) -> str:
    """Call the upstream cell through the module it is actually importable from.

    A ``VAR_KEYWORD`` parameter is forwarded by unpacking (``**kwargs``), not as a
    literal keyword argument named e.g. ``kwargs=kwargs`` — the latter would pass a dict
    as a single keyword argument instead of forwarding the caller's kwargs.
    """
    alias = REGISTRY_ALIAS[spec.registry_module]
    call_args = [
        f"**{p}" if param.kind is param.VAR_KEYWORD else f"{p}={p}"
        for p, param in spec.signature.parameters.items()
    ]
    args = ",\n        ".join(call_args)
    if not args:
        return f"return {alias}.{spec.name}()"
    return f"return {alias}.{spec.name}(\n        {args},\n    )"


def _render_decorator(spec: CellSpec) -> str:
    parts = []
    if spec.tags:
        parts.append(f"tags={list(spec.tags)!r}")
    if spec.schematic_function:
        parts.append(f"schematic_function={spec.schematic_function}")
    if not parts:
        return "@gf.cell"
    return "@gf.cell(" + ", ".join(parts) + ")"


def _render_docstring_body(docstring: str) -> str:
    r"""Render a docstring's lines indented under a wrapper's 4-space body indent.

    Blank lines get no trailing indent: upstream docstrings sometimes have trailing
    whitespace on otherwise-blank lines (W293), which `ruff format`/`ruff check --fix`
    both treat as an unsafe fix and leave alone. Naively joining with ``"\\n    "``
    would itself *introduce* W293 on every blank line (the separator's indent lands
    before an empty line). Pre-commit's generic trailing-whitespace hook would strip
    that from the *committed* file regardless — but if the generator doesn't also avoid
    emitting it, a fresh `--check` regeneration would permanently disagree with the
    committed (post-hook) file, breaking the round-trip guarantee `make cells-check`
    depends on.
    """
    lines = [line.rstrip() for line in docstring.splitlines()]
    if not lines:
        return ""
    first, *rest = lines
    for line in rest:
        first += f"\n    {line}" if line else "\n"
    return first


def render_module(category: str, specs: list[CellSpec]) -> str:
    """Render one category module as Python source."""
    specs = sorted(specs, key=lambda s: s.name)
    schematics = sorted({s.schematic_function for s in specs if s.schematic_function})

    bodies: list[str] = []
    # name -> the (first, alphabetically-by-cell-name) source module that needs it.
    # Every name needed by a non-literal default is imported exactly once, aliased
    # (see _alias_for) — this both de-duplicates names re-exported identically from
    # multiple sibling gdsfactory modules, and avoids a bare import ever colliding
    # with a same-named cell generated later in this module.
    needed_by_name: dict[str, str] = {}
    for spec in specs:
        params, needed = _render_signature(spec, spec.source_defaults)
        for name in needed:
            needed_by_name.setdefault(name, spec.source_module)
        doc = _render_docstring_body(spec.docstring)
        bodies.append(
            f"{_render_decorator(spec)}\n"
            f"def {spec.name}(\n    {params},\n) -> gf.Component:\n"
            f'    r"""{doc}\n    """\n'
            f"    {_render_call(spec)}\n"
        )

    upstream_names: dict[str, set[str]] = defaultdict(set)
    for name, module in needed_by_name.items():
        upstream_names[module].add(name)

    lines = [HEADER.format(summary=f"Generated {category} cells.")]
    if any(_has_mutable_default(spec) for spec in specs):
        # File-level, not per-cell: faithfully re-emitting gdsfactory's own mutable
        # default is the point of this generator (see _render_signature), so B006 is
        # suppressed for the whole module rather than per-line — a per-line comment
        # would need to land on whatever line `ruff format` leaves the diagnostic
        # anchored to, which shifts when it rewraps a long literal.
        lines.append("# ruff: noqa: B006")
    for registry_module in sorted({s.registry_module for s in specs}):
        alias = REGISTRY_ALIAS[registry_module]
        package, _, leaf = registry_module.rpartition(".")
        lines.append(f"from {package} import {leaf} as {alias}")
    for module in sorted(upstream_names):
        names = ",\n    ".join(
            f"{n} as {_alias_for(n)}" for n in sorted(upstream_names[module])
        )
        lines.append(f"from {module} import (\n    {names},\n)")
    if schematics:
        lines.append(
            "from gpdk.cells._schematic import (\n    "
            + ",\n    ".join(schematics)
            + ",\n)"
        )
    lines.append("")
    lines.extend(bodies)
    lines.append(
        "\n__all__ = [\n    " + ",\n    ".join(repr(s.name) for s in specs) + ",\n]\n"
    )
    return "\n".join(lines)


def render_schematic_module(specs: dict[str, CellSpec]) -> str:
    """Re-export the gdsfactory schematic functions the wrappers reference."""
    names = sorted(
        {s.schematic_function for s in specs.values() if s.schematic_function}
    )
    body = ",\n    ".join(names)
    return (
        '"""Re-exported gdsfactory schematic functions.\n\n'
        "Generated by .github/generate_cells.py. Do not edit by hand.\n"
        '"""\n\n'
        f"from {SCHEMATIC_MODULE} import (\n    {body},\n)\n\n"
        f"__all__ = [\n    " + ",\n    ".join(repr(n) for n in names) + ",\n]\n"
    )


def render_init(categories: list[str]) -> str:
    """Render cells/__init__.py re-exporting every category module.

    Uses relative imports (``from .analog import *``), not absolute
    (``from gpdk.cells.analog import *``): the ``check-cells-structure`` pre-commit hook
    (pdk-ci-workflow-public) only recognizes a module as re-exported via a relative
    ``ImportFrom`` (``node.level >= 1``) or a plain ``import``, not an absolute
    ``ImportFrom``. ``_schematic`` is included too, since it is a real file under
    ``gpdk/cells/`` that the same hook requires every module to be re-exported from.
    """
    modules = sorted([*categories, "_schematic"])
    imports = "\n".join(f"from .{m} import *  # noqa: F403" for m in modules)
    return (
        '"""Generated cell library.\n\n'
        "Generated by .github/generate_cells.py. Do not edit by hand.\n"
        '"""\n\n'
        f"{imports}\n"
    )


def write_all(root: pathlib.Path) -> dict[pathlib.Path, str]:
    """Render every file and write it under ``root``, then ruff-format the tree."""
    specs = collect_cells()
    by_category: dict[str, list[CellSpec]] = defaultdict(list)
    for spec in specs.values():
        by_category[spec.category].append(spec)

    root.mkdir(parents=True, exist_ok=True)
    for category, group in by_category.items():
        source = render_module(category, group)
        compile(source, f"{category}.py", "exec")
        (root / f"{category}.py").write_text(source)
    (root / "_schematic.py").write_text(render_schematic_module(specs))
    (root / "__init__.py").write_text(render_init(list(by_category)))

    subprocess.run(
        [sys.executable, "-m", "ruff", "format", str(root)],
        check=True,
        capture_output=True,
    )
    subprocess.run(
        [sys.executable, "-m", "ruff", "check", "--fix", str(root)],
        check=False,
        capture_output=True,
    )
    return {p: p.read_text() for p in sorted(root.glob("*.py"))}


def main() -> int:
    """Entry point for --write and --check."""
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true", help="regenerate gpdk/cells/")
    group.add_argument(
        "--check", action="store_true", help="fail if gpdk/cells/ is stale"
    )
    args = parser.parse_args()

    if args.write:
        write_all(CELLS_DIR)
        print(f"wrote {len(list(CELLS_DIR.glob('*.py')))} modules to {CELLS_DIR}")
        return 0

    with tempfile.TemporaryDirectory() as tmp:
        expected = write_all(pathlib.Path(tmp))
        actual = {p.name: p.read_text() for p in sorted(CELLS_DIR.glob("*.py"))}
        expected_by_name = {p.name: text for p, text in expected.items()}

    failed = False
    for name in sorted(set(expected_by_name) | set(actual)):
        want = expected_by_name.get(name, "")
        have = actual.get(name, "")
        if want != have:
            failed = True
            sys.stdout.writelines(
                difflib.unified_diff(
                    have.splitlines(keepends=True),
                    want.splitlines(keepends=True),
                    fromfile=f"committed/{name}",
                    tofile=f"generated/{name}",
                )
            )

    if failed:
        print(
            "\ngpdk/cells/ does not match the pinned gdsfactory.\n"
            "Run `make cells-regen`, then regenerate test references with "
            "`make test-force`.",
            file=sys.stderr,
        )
        return 1
    print("gpdk/cells/ matches the pinned gdsfactory")
    return 0


if __name__ == "__main__":
    sys.exit(main())
